
/*
  Copyright (c) 2010, Nicolas Garcia Belmonte
  All rights reserved

  > Redistribution and use in source and binary forms, with or without
  > modification, are permitted provided that the following conditions are met:
  >      * Redistributions of source code must retain the above copyright
  >        notice, this list of conditions and the following disclaimer.
  >      * Redistributions in binary form must reproduce the above copyright
  >        notice, this list of conditions and the following disclaimer in the
  >        documentation and/or other materials provided with the distribution.
  >      * Neither the name of the organization nor the
  >        names of its contributors may be used to endorse or promote products
  >        derived from this software without specific prior written permission.
  >
  >  THIS SOFTWARE IS PROVIDED BY NICOLAS GARCIA BELMONTE ``AS IS'' AND ANY
  >  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
  >  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
  >  DISCLAIMED. IN NO EVENT SHALL NICOLAS GARCIA BELMONTE BE LIABLE FOR ANY
  >  DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
  >  (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
  >  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
  >  ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
  >  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
  >  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
 
 (function(){window.$jit=function(a){a=a||window;for(var b in $jit)if($jit[b].$extend)a[b]=$jit[b]};$jit.version="2.0.0b";var i=function(a){return document.getElementById(a)};i.empty=function(){};i.extend=function(a,b){for(var c in b||{})a[c]=b[c];return a};i.lambda=function(a){return typeof a=="function"?a:function(){return a}};i.time=Date.now||function(){return+new Date};i.splat=function(a){var b=i.type(a);return b?b!="array"?[a]:a:[]};i.type=function(a){var b=i.type.s.call(a).match(/^\[object\s(.*)\]$/)[1].toLowerCase();
if(b!="object")return b;if(a&&a.$$family)return a.$$family;return a&&a.nodeName&&a.nodeType==1?"element":b};i.type.s=Object.prototype.toString;i.each=function(a,b){if(i.type(a)=="object")for(var c in a)b(a[c],c);else{c=0;for(var d=a.length;c<d;c++)b(a[c],c)}};i.indexOf=function(a,b){if(Array.indexOf)return a.indexOf(b);for(var c=0,d=a.length;c<d;c++)if(a[c]===b)return c;return-1};i.map=function(a,b){var c=[];i.each(a,function(d,e){c.push(b(d,e))});return c};i.reduce=function(a,b,c){var d=a.length;
if(d==0)return c;for(var e=arguments.length==3?c:a[--d];d--;)e=b(e,a[d]);return e};i.merge=function(){for(var a={},b=0,c=arguments.length;b<c;b++){var d=arguments[b];if(i.type(d)=="object")for(var e in d){var f=d[e],g=a[e];a[e]=g&&i.type(f)=="object"&&i.type(g)=="object"?i.merge(g,f):i.unlink(f)}}return a};i.unlink=function(a){var b;switch(i.type(a)){case "object":b={};for(var c in a)b[c]=i.unlink(a[c]);break;case "array":b=[];c=0;for(var d=a.length;c<d;c++)b[c]=i.unlink(a[c]);break;default:return a}return b};
i.zip=function(){if(arguments.length===0)return[];for(var a=0,b=[],c=arguments.length,d=arguments[0].length;a<d;a++){for(var e=0,f=[];e<c;e++)f.push(arguments[e][a]);b.push(f)}return b};i.rgbToHex=function(a,b){if(a.length<3)return null;if(a.length==4&&a[3]==0&&!b)return"transparent";for(var c=[],d=0;d<3;d++){var e=(a[d]-0).toString(16);c.push(e.length==1?"0"+e:e)}return b?c:"#"+c.join("")};i.hexToRgb=function(a){if(a.length!=7){a=a.match(/^#?(\w{1,2})(\w{1,2})(\w{1,2})$/);a.shift();if(a.length!=
3)return null;for(var b=[],c=0;c<3;c++){var d=a[c];if(d.length==1)d+=d;b.push(parseInt(d,16))}return b}else{a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]}};i.destroy=function(a){i.clean(a);a.parentNode&&a.parentNode.removeChild(a);a.clearAttributes&&a.clearAttributes()};i.clean=function(a){a=a.childNodes;for(var b=0,c=a.length;b<c;b++)i.destroy(a[b])};i.addEvent=function(a,b,c){a.addEventListener?a.addEventListener(b,c,false):a.attachEvent("on"+b,c)};i.addEvents=function(a,b){for(var c in b)i.addEvent(a,
c,b[c])};i.hasClass=function(a,b){return(" "+a.className+" ").indexOf(" "+b+" ")>-1};i.addClass=function(a,b){if(!i.hasClass(a,b))a.className=a.className+" "+b};i.removeClass=function(a,b){a.className=a.className.replace(RegExp("(^|\\s)"+b+"(?:\\s|$)"),"$1")};i.getPos=function(a){var b=function(c){for(var d={x:0,y:0};c&&!/^(?:body|html)$/i.test(c.tagName);){d.x+=c.offsetLeft;d.y+=c.offsetTop;c=c.offsetParent}return d}(a);a=function(c){for(var d={x:0,y:0};c&&!/^(?:body|html)$/i.test(c.tagName);){d.x+=
c.scrollLeft;d.y+=c.scrollTop;c=c.parentNode}return d}(a);return{x:b.x-a.x,y:b.y-a.y}};i.event={get:function(a,b){b=b||window;return a||b.event},getWheel:function(a){return a.wheelDelta?a.wheelDelta/120:-(a.detail||0)/3},isRightClick:function(a){return a.which==3||a.button==2},getPos:function(a,b){b=b||window;a=a||b.event;var c=b.document;c=c.documentElement||c.body;if(a.touches&&a.touches.length)a=a.touches[0];return{x:a.pageX||a.clientX+c.scrollLeft,y:a.pageY||a.clientY+c.scrollTop}},stop:function(a){a.stopPropagation&&
a.stopPropagation();a.cancelBubble=true;if(a.preventDefault)a.preventDefault();else a.returnValue=false}};$jit.util=$jit.id=i;var o=function(a){a=a||{};var b=function(){for(var d in this)if(typeof this[d]!="function")this[d]=i.unlink(this[d]);this.constructor=b;if(o.prototyping)return this;d=this.initialize?this.initialize.apply(this,arguments):this;this.$$family="class";return d},c;for(c in o.Mutators)if(a[c]){a=o.Mutators[c](a,a[c]);delete a[c]}i.extend(b,this);b.constructor=o;b.prototype=a;return b};
o.Mutators={Implements:function(a,b){i.each(i.splat(b),function(c){o.prototyping=c;c=typeof c=="function"?new c:c;for(var d in c)d in a||(a[d]=c[d]);delete o.prototyping});return a}};i.extend(o,{inherit:function(a,b){for(var c in b){var d=b[c],e=a[c],f=i.type(d);if(e&&f=="function")d!=e&&o.override(a,c,d);else a[c]=f=="object"?i.merge(e,d):d}return a},override:function(a,b,c){var d=o.prototyping;if(d&&a[b]!=d[b])d=null;a[b]=function(){var e=this.parent;this.parent=d?d[b]:a[b];var f=c.apply(this,arguments);
this.parent=e;return f}}});o.prototype.implement=function(){var a=this.prototype;i.each(Array.prototype.slice.call(arguments||[]),function(b){o.inherit(a,b)});return this};$jit.Class=o;$jit.json={prune:function(a,b){this.each(a,function(c,d){if(d==b&&c.children){delete c.children;c.children=[]}})},getParent:function(a,b){if(a.id==b)return false;var c=a.children;if(c&&c.length>0)for(var d=0;d<c.length;d++)if(c[d].id==b)return a;else{var e=this.getParent(c[d],b);if(e)return e}return false},getSubtree:function(a,
b){if(a.id==b)return a;for(var c=0,d=a.children;c<d.length;c++){var e=this.getSubtree(d[c],b);if(e!=null)return e}return null},eachLevel:function(a,b,c,d){if(b<=c){d(a,b);if(a.children){var e=0;for(a=a.children;e<a.length;e++)this.eachLevel(a[e],b+1,c,d)}}},each:function(a,b){this.eachLevel(a,0,Number.MAX_VALUE,b)}};$jit.Trans={$extend:true,linear:function(a){return a}};var M=$jit.Trans;(function(){var a=function(b,c){c=i.splat(c);return i.extend(b,{easeIn:function(d){return b(d,c)},easeOut:function(d){return 1-
b(1-d,c)},easeInOut:function(d){return d<=0.5?b(2*d,c)/2:(2-b(2*(1-d),c))/2}})};i.each({Pow:function(b,c){return Math.pow(b,c[0]||6)},Expo:function(b){return Math.pow(2,8*(b-1))},Circ:function(b){return 1-Math.sin(Math.acos(b))},Sine:function(b){return 1-Math.sin((1-b)*Math.PI/2)},Back:function(b,c){c=c[0]||1.618;return Math.pow(b,2)*((c+1)*b-c)},Bounce:function(b){for(var c,d=0,e=1;;d+=e,e/=2)if(b>=(7-4*d)/11){c=e*e-Math.pow((11-6*d-11*b)/4,2);break}return c},Elastic:function(b,c){return Math.pow(2,
10*--b)*Math.cos(20*b*Math.PI*(c[0]||1)/3)}},function(b,c){M[c]=a(b)});i.each(["Quad","Cubic","Quart","Quint"],function(b,c){M[b]=a(function(d){return Math.pow(d,[c+2])})})})();var P=new o({initialize:function(a){this.setOptions(a)},setOptions:function(a){this.opt=i.merge({duration:2500,fps:40,transition:M.Quart.easeInOut,compute:i.empty,complete:i.empty,link:"ignore"},a||{});return this},step:function(){var a=i.time(),b=this.opt;if(a<this.time+b.duration){a=b.transition((a-this.time)/b.duration);
b.compute(a)}else{this.timer=clearInterval(this.timer);b.compute(1);b.complete()}},start:function(){if(!this.check())return this;this.time=0;this.startTimer();return this},startTimer:function(){var a=this,b=this.opt.fps;if(this.timer)return false;this.time=i.time()-this.time;this.timer=setInterval(function(){a.step()},Math.round(1E3/b));return true},pause:function(){this.stopTimer();return this},resume:function(){this.startTimer();return this},stopTimer:function(){if(!this.timer)return false;this.time=
i.time()-this.time;this.timer=clearInterval(this.timer);return true},check:function(){if(!this.timer)return true;if(this.opt.link=="cancel"){this.stopTimer();return true}return false}}),x=function(){for(var a=arguments,b=0,c=a.length,d={};b<c;b++){var e=x[a[b]];if(e.$extend)i.extend(d,e);else d[a[b]]=e}return d};x.PieChart={$extend:true,animate:true,offset:25,sliceOffset:0,labelOffset:3,type:"stacked",hoveredColor:"#9fd4ff",Events:{enable:false,onClick:i.empty},Tips:{enable:false,onShow:i.empty,onHide:i.empty},
showLabels:true,resizeLabels:false,updateHeights:false};x.Canvas={$extend:true,injectInto:"id",width:false,height:false,useCanvas:false,withLabels:true,background:false};x.Node={$extend:false,overridable:false,type:"circle",color:"#ccb",alpha:1,dim:3,height:20,width:90,autoHeight:false,autoWidth:false,lineWidth:1,transform:true,align:"center",angularWidth:1,span:1,CanvasStyles:{}};x.Edge={$extend:false,overridable:false,type:"line",color:"#ccb",lineWidth:1,dim:15,alpha:1,epsilon:7,CanvasStyles:{}};
x.Fx={$extend:true,fps:40,duration:2500,transition:$jit.Trans.Quart.easeInOut,clearCanvas:true};x.Label={$extend:false,overridable:false,type:"HTML",style:" ",size:10,family:"sans-serif",textAlign:"center",textBaseline:"alphabetic",color:"#fff"};x.Tips={$extend:false,enable:false,type:"auto",offsetX:20,offsetY:20,force:false,onShow:i.empty,onHide:i.empty};x.NodeStyles={$extend:false,enable:false,type:"auto",stylesHover:false,stylesClick:false};x.Events={$extend:false,enable:false,enableForEdges:false,
type:"auto",onClick:i.empty,onRightClick:i.empty,onMouseMove:i.empty,onMouseEnter:i.empty,onMouseLeave:i.empty,onDragStart:i.empty,onDragMove:i.empty,onDragCancel:i.empty,onDragEnd:i.empty,onTouchStart:i.empty,onTouchMove:i.empty,onTouchEnd:i.empty,onMouseWheel:i.empty};x.Navigation={$extend:false,enable:false,type:"auto",panning:false,zooming:false};x.Controller={$extend:true,onBeforeCompute:i.empty,onAfterCompute:i.empty,onCreateLabel:i.empty,onPlaceLabel:i.empty,onComplete:i.empty,onBeforePlotLine:i.empty,
onAfterPlotLine:i.empty,onBeforePlotNode:i.empty,onAfterPlotNode:i.empty,request:false};var E={initialize:function(a,b){this.viz=b;this.canvas=b.canvas;this.config=b.config[a];this.nodeTypes=b.fx.nodeTypes;var c=this.config.type;this.labelContainer=(this.dom=c=="auto"?b.config.Label.type!="Native":c!="Native")&&b.labels.getLabelContainer();this.isEnabled()&&this.initializePost()},initializePost:i.empty,setAsProperty:i.lambda(false),isEnabled:function(){return this.config.enable},isLabel:function(a,
b){a=i.event.get(a,b);var c=this.labelContainer,d=a.target||a.srcElement;if(d&&d.parentNode==c)return d;return false}},v={onMouseUp:i.empty,onMouseDown:i.empty,onMouseMove:i.empty,onMouseOver:i.empty,onMouseOut:i.empty,onMouseWheel:i.empty,onTouchStart:i.empty,onTouchMove:i.empty,onTouchEnd:i.empty,onTouchCancel:i.empty},S=new o({initialize:function(a){this.viz=a;this.canvas=a.canvas;this.edge=this.node=false;this.registeredObjects=[];this.attachEvents()},attachEvents:function(){var a=this.canvas.getElement(),
b=this;a.oncontextmenu=i.lambda(false);i.addEvents(a,{mouseup:function(d,e){var f=i.event.get(d,e);b.handleEvent("MouseUp",d,e,b.makeEventObject(d,e),i.event.isRightClick(f))},mousedown:function(d,e){var f=i.event.get(d,e);b.handleEvent("MouseDown",d,e,b.makeEventObject(d,e),i.event.isRightClick(f))},mousemove:function(d,e){b.handleEvent("MouseMove",d,e,b.makeEventObject(d,e))},mouseover:function(d,e){b.handleEvent("MouseOver",d,e,b.makeEventObject(d,e))},mouseout:function(d,e){b.handleEvent("MouseOut",
d,e,b.makeEventObject(d,e))},touchstart:function(d,e){b.handleEvent("TouchStart",d,e,b.makeEventObject(d,e))},touchmove:function(d,e){b.handleEvent("TouchMove",d,e,b.makeEventObject(d,e))},touchend:function(d,e){b.handleEvent("TouchEnd",d,e,b.makeEventObject(d,e))}});var c=function(d,e){var f=i.event.get(d,e);f=i.event.getWheel(f);b.handleEvent("MouseWheel",d,e,f)};!document.getBoxObjectFor&&window.mozInnerScreenX==null?i.addEvent(a,"mousewheel",c):a.addEventListener("DOMMouseScroll",c,false)},register:function(a){this.registeredObjects.push(a)},
handleEvent:function(){for(var a=Array.prototype.slice.call(arguments),b=a.shift(),c=0,d=this.registeredObjects,e=d.length;c<e;c++)d[c]["on"+b].apply(d[c],a)},makeEventObject:function(a,b){var c=this,d=this.viz.graph,e=this.viz.fx,f=e.nodeTypes,g=e.edgeTypes;return{pos:false,node:false,edge:false,contains:false,getNodeCalled:false,getEdgeCalled:false,getPos:function(){var h=c.viz.canvas,j=h.getSize(),k=h.getPos(),l=h.translateOffsetX,m=h.translateOffsetY,n=h.scaleOffsetX;h=h.scaleOffsetY;var p=i.event.getPos(a,
b);return this.pos={x:(p.x-k.x-j.width/2-l)*1/n,y:(p.y-k.y-j.height/2-m)*1/h}},getNode:function(){if(this.getNodeCalled)return this.node;this.getNodeCalled=true;for(var h in d.nodes){var j=d.nodes[h],k=j&&f[j.getData("type")];if(k=k&&k.contains&&k.contains.call(e,j,this.getPos())){this.contains=k;return c.node=this.node=j}}return c.node=this.node=false},getEdge:function(){if(this.getEdgeCalled)return this.edge;this.getEdgeCalled=true;var h={},j;for(j in d.edges){var k=d.edges[j];h[j]=true;for(var l in k)if(!(l in
h)){var m=k[l],n=m&&g[m.getData("type")];if(n=n&&n.contains&&n.contains.call(e,m,this.getPos())){this.contains=n;return c.edge=this.edge=m}}}return c.edge=this.edge=false},getContains:function(){if(this.getNodeCalled)return this.contains;this.getNode();return this.contains}}}}),B={initializeExtras:function(){var a=new S(this),b=this;i.each(["NodeStyles","Tips","Navigation","Events"],function(c){var d=new B.Classes[c](c,b);d.isEnabled()&&a.register(d);if(d.setAsProperty())b[c.toLowerCase()]=d})}};
B.Classes={};B.Classes.Events=new o({Implements:[E,v],initializePost:function(){this.fx=this.viz.fx;this.ntypes=this.viz.fx.nodeTypes;this.etypes=this.viz.fx.edgeTypes;this.moved=this.touchMoved=this.touched=this.pressed=this.hovered=false},setAsProperty:i.lambda(true),onMouseUp:function(a,b,c,d){a=i.event.get(a,b);this.moved||(d?this.config.onRightClick(this.hovered,c,a):this.config.onClick(this.pressed,c,a));if(this.pressed){this.moved?this.config.onDragEnd(this.pressed,c,a):this.config.onDragCancel(this.pressed,
c,a);this.pressed=this.moved=false}},onMouseOut:function(a,b,c){var d=i.event.get(a,b),e;if(this.dom&&(e=this.isLabel(a,b))){this.config.onMouseLeave(this.viz.graph.getNode(e.id),c,d);this.hovered=false}else{a=d.relatedTarget;for(b=this.canvas.getElement();a&&a.parentNode;){if(b==a.parentNode)return;a=a.parentNode}if(this.hovered){this.config.onMouseLeave(this.hovered,c,d);this.hovered=false}}},onMouseOver:function(a,b,c){var d=i.event.get(a,b),e;if(this.dom&&(e=this.isLabel(a,b))){this.hovered=this.viz.graph.getNode(e.id);
this.config.onMouseEnter(this.hovered,c,d)}},onMouseMove:function(a,b,c){a=i.event.get(a,b);if(this.pressed){this.moved=true;this.config.onDragMove(this.pressed,c,a)}else if(this.dom)this.config.onMouseMove(this.hovered,c,a);else{if(this.hovered){b=this.hovered;var d=b.nodeFrom?this.etypes[b.getData("type")]:this.ntypes[b.getData("type")];if(d&&d.contains&&d.contains.call(this.fx,b,c.getPos())){this.config.onMouseMove(b,c,a);return}else{this.config.onMouseLeave(b,c,a);this.hovered=false}}(this.hovered=
c.getNode()||this.config.enableForEdges&&c.getEdge())?this.config.onMouseEnter(this.hovered,c,a):this.config.onMouseMove(false,c,a)}},onMouseWheel:function(a,b,c){this.config.onMouseWheel(c,i.event.get(a,b))},onMouseDown:function(a,b,c){a=i.event.get(a,b);this.pressed=c.getNode()||this.config.enableForEdges&&c.getEdge();this.config.onDragStart(this.pressed,c,a)},onTouchStart:function(a,b,c){a=i.event.get(a,b);this.touched=c.getNode()||this.config.enableForEdges&&c.getEdge();this.config.onTouchStart(this.touched,
c,a)},onTouchMove:function(a,b,c){a=i.event.get(a,b);if(this.touched){this.touchMoved=true;this.config.onTouchMove(this.touched,c,a)}},onTouchEnd:function(a,b,c){a=i.event.get(a,b);if(this.touched){this.touchMoved?this.config.onTouchEnd(this.touched,c,a):this.config.onTouchCancel(this.touched,c,a);this.touched=this.touchMoved=false}}});B.Classes.Tips=new o({Implements:[E,v],initializePost:function(){if(document.body){var a=i("_tooltip")||document.createElement("div");a.id="_tooltip";a.className="tip";
i.extend(a.style,{position:"absolute",display:"none",zIndex:13E3});document.body.appendChild(a);this.tip=a;this.node=false}},setAsProperty:i.lambda(true),onMouseOut:function(a,b){if(this.dom&&this.isLabel(a,b))this.hide(true);else{for(var c=a.relatedTarget,d=this.canvas.getElement();c&&c.parentNode;){if(d==c.parentNode)return;c=c.parentNode}this.hide(false)}},onMouseOver:function(a,b){var c;if(this.dom&&(c=this.isLabel(a,b))){this.node=this.viz.graph.getNode(c.id);this.config.onShow(this.tip,this.node,
c)}},onMouseMove:function(a,b,c){this.dom&&this.isLabel(a,b)&&this.setTooltipPosition(i.event.getPos(a,b));if(!this.dom){var d=c.getNode();if(d){if(this.config.force||!this.node||this.node.id!=d.id){this.node=d;this.config.onShow(this.tip,d,c.getContains())}this.setTooltipPosition(i.event.getPos(a,b))}else this.hide(true)}},setTooltipPosition:function(a){var b=this.tip,c=b.style,d=this.config;c.display="";var e={height:document.body.clientHeight,width:document.body.clientWidth};b={width:b.offsetWidth,
height:b.offsetHeight};var f=d.offsetX;d=d.offsetY;c.top=(a.y+d+b.height>e.height?a.y-b.height-d:a.y+d)+"px";c.left=(a.x+b.width+f>e.width?a.x-b.width-f:a.x+f)+"px"},hide:function(a){this.tip.style.display="none";a&&this.config.onHide()}});B.Classes.NodeStyles=new o({Implements:[E,v],initializePost:function(){this.fx=this.viz.fx;this.types=this.viz.fx.nodeTypes;this.nStyles=this.config;this.nodeStylesOnHover=this.nStyles.stylesHover;this.nodeStylesOnClick=this.nStyles.stylesClick;this.hoveredNode=
false;this.fx.nodeFxAnimation=new P;this.move=this.down=false},onMouseOut:function(a,b){this.down=this.move=false;if(this.hoveredNode){this.dom&&this.isLabel(a,b)&&this.toggleStylesOnHover(this.hoveredNode,false);for(var c=a.relatedTarget,d=this.canvas.getElement();c&&c.parentNode;){if(d==c.parentNode)return;c=c.parentNode}this.toggleStylesOnHover(this.hoveredNode,false);this.hoveredNode=false}},onMouseOver:function(a,b){var c;if(this.dom&&(c=this.isLabel(a,b))){c=this.viz.graph.getNode(c.id);if(!c.selected){this.hoveredNode=
c;this.toggleStylesOnHover(this.hoveredNode,true)}}},onMouseDown:function(a,b,c,d){if(!d){var e;if(this.dom&&(e=this.isLabel(a,b)))this.down=this.viz.graph.getNode(e.id);else if(!this.dom)this.down=c.getNode();this.move=false}},onMouseUp:function(a,b,c,d){if(!d){this.move||this.onClick(c.getNode());this.down=this.move=false}},getRestoredStyles:function(a,b){var c={},d=this["nodeStylesOn"+b],e;for(e in d)c[e]=a.styles["$"+e];return c},toggleStylesOnHover:function(a,b){this.nodeStylesOnHover&&this.toggleStylesOn("Hover",
a,b)},toggleStylesOnClick:function(a,b){this.nodeStylesOnClick&&this.toggleStylesOn("Click",a,b)},toggleStylesOn:function(a,b,c){var d=this.viz;if(c){if(!b.styles)b.styles=i.merge(b.data,{});for(var e in this["nodeStylesOn"+a]){c="$"+e;c in b.styles||(b.styles[c]=b.getData(e))}d.fx.nodeFx(i.extend({elements:{id:b.id,properties:this["nodeStylesOn"+a]},transition:M.Quart.easeOut,duration:300,fps:40},this.config))}else{a=this.getRestoredStyles(b,a);d.fx.nodeFx(i.extend({elements:{id:b.id,properties:a},
transition:M.Quart.easeOut,duration:300,fps:40},this.config))}},onClick:function(a){if(a){var b=this.nodeStylesOnClick;if(b)if(a.selected){this.toggleStylesOnClick(a,false);delete a.selected}else{this.viz.graph.eachNode(function(c){if(c.selected){for(var d in b)c.setData(d,c.styles["$"+d],"end");delete c.selected}});this.toggleStylesOnClick(a,true);a.selected=true;delete a.hovered;this.hoveredNode=false}}},onMouseMove:function(a,b,c){if(this.down)this.move=true;if(!(this.dom&&this.isLabel(a,b))){var d=
this.nodeStylesOnHover;if(d)if(!this.dom){if(this.hoveredNode)if((a=this.types[this.hoveredNode.getData("type")])&&a.contains&&a.contains.call(this.fx,this.hoveredNode,c.getPos()))return;c=c.getNode();if(this.hoveredNode||c)if(!c.hovered)if(c&&!c.selected){this.fx.nodeFxAnimation.stopTimer();this.viz.graph.eachNode(function(e){if(e.hovered&&!e.selected){for(var f in d)e.setData(f,e.styles["$"+f],"end");delete e.hovered}});c.hovered=true;this.hoveredNode=c;this.toggleStylesOnHover(c,true)}else if(this.hoveredNode&&
!this.hoveredNode.selected){this.fx.nodeFxAnimation.stopTimer();this.toggleStylesOnHover(this.hoveredNode,false);delete this.hoveredNode.hovered;this.hoveredNode=false}}}}});B.Classes.Navigation=new o({Implements:[E,v],initializePost:function(){this.pressed=this.pos=false},onMouseWheel:function(a,b,c){if(this.config.zooming){i.event.stop(i.event.get(a,b));a=1+c*(this.config.zooming/1E3);this.canvas.scale(a,a)}},onMouseDown:function(a,b,c){if(this.config.panning)if(!(this.config.panning=="avoid nodes"&&
c.getNode())){this.pressed=true;this.pos=c.getPos();a=this.canvas;b=a.translateOffsetX;c=a.translateOffsetY;var d=a.scaleOffsetY;this.pos.x*=a.scaleOffsetX;this.pos.x+=b;this.pos.y*=d;this.pos.y+=c}},onMouseMove:function(a,b,c){if(this.config.panning)if(this.pressed)if(!(this.config.panning=="avoid nodes"&&c.getNode())){a=this.pos;c=c.getPos();var d=this.canvas,e=d.translateOffsetX,f=d.translateOffsetY;b=d.scaleOffsetX;d=d.scaleOffsetY;c.x*=b;c.y*=d;c.x+=e;c.y+=f;e=c.x-a.x;a=c.y-a.y;this.pos=c;this.canvas.translate(e*
1/b,a*1/d)}},onMouseUp:function(){if(this.config.panning)this.pressed=false}});var F;(function(){function a(d,e){var f=document.createElement(d),g;for(g in e)if(typeof e[g]=="object")i.extend(f[g],e[g]);else f[g]=e[g];if(d=="canvas"&&!c&&G_vmlCanvasManager)f=G_vmlCanvasManager.initElement(document.body.appendChild(f));return f}var b=typeof HTMLCanvasElement,c=b=="object"||b=="function";$jit.Canvas=F=new o({canvases:[],pos:false,element:false,labelContainer:false,translateOffsetX:0,translateOffsetY:0,
scaleOffsetX:1,scaleOffsetY:1,initialize:function(d,e){this.viz=d;this.opt=e;var f=i.type(e.injectInto)=="string"?e.injectInto:e.injectInto.id,g=f+"-label",h=i(f),j=e.width||h.offsetWidth,k=e.height||h.offsetHeight;this.id=f;var l={injectInto:f,width:j,height:k};this.element=a("div",{id:f+"-canvaswidget",style:{position:"relative",width:j+"px",height:k+"px"}});this.labelContainer=this.createLabelContainer(e.Label.type,g,l);this.canvases.push(new F.Base({config:i.extend({idSuffix:"-canvas"},l),plot:function(){d.fx.plot()},
resize:function(){d.refresh()}}));if(f=e.background){l=new F.Background[f.type](d,i.extend(f,l));this.canvases.push(new F.Base(l))}for(l=this.canvases.length;l--;){this.element.appendChild(this.canvases[l].canvas);l>0&&this.canvases[l].plot()}this.element.appendChild(this.labelContainer);h.appendChild(this.element);var m=null,n=this;i.addEvent(window,"scroll",function(){clearTimeout(m);m=setTimeout(function(){n.getPos(true)},500)})},getCtx:function(d){return this.canvases[d||0].getCtx()},getConfig:function(){return this.opt},
getElement:function(){return this.element},getSize:function(d){return this.canvases[d||0].getSize()},resize:function(d,e){this.getPos(true);this.translateOffsetX=this.translateOffsetY=0;this.scaleOffsetX=this.scaleOffsetY=1;for(var f=0,g=this.canvases.length;f<g;f++)this.canvases[f].resize(d,e);f=this.element.style;f.width=d+"px";f.height=e+"px";if(this.labelContainer)this.labelContainer.style.width=d+"px"},translate:function(d,e,f){this.translateOffsetX+=d*this.scaleOffsetX;this.translateOffsetY+=
e*this.scaleOffsetY;for(var g=0,h=this.canvases.length;g<h;g++)this.canvases[g].translate(d,e,f)},scale:function(d,e){var f=this.scaleOffsetX*d,g=this.scaleOffsetY*e,h=this.translateOffsetX*(d-1)/f,j=this.translateOffsetY*(e-1)/g;this.scaleOffsetX=f;this.scaleOffsetY=g;f=0;for(g=this.canvases.length;f<g;f++)this.canvases[f].scale(d,e,true);this.translate(h,j,false)},getPos:function(d){if(d||!this.pos)return this.pos=i.getPos(this.getElement());return this.pos},clear:function(d){this.canvases[d||0].clear()},
path:function(d,e){var f=this.canvases[0].getCtx();f.beginPath();e(f);f[d]();f.closePath()},createLabelContainer:function(d,e,f){if(d=="HTML"||d=="Native")return a("div",{id:e,style:{overflow:"visible",position:"absolute",top:0,left:0,width:f.width+"px",height:0}});else if(d=="SVG"){d=document.createElementNS("http://www.w3.org/2000/svg","svg:svg");d.setAttribute("width",f.width);d.setAttribute("height",f.height);var g=d.style;g.position="absolute";g.left=g.top="0px";g=document.createElementNS("http://www.w3.org/2000/svg",
"svg:g");g.setAttribute("width",f.width);g.setAttribute("height",f.height);g.setAttribute("x",0);g.setAttribute("y",0);g.setAttribute("id",e);d.appendChild(g);return d}}});F.Base=new o({translateOffsetX:0,translateOffsetY:0,scaleOffsetX:1,scaleOffsetY:1,initialize:function(d){this.viz=d;this.opt=d.config;this.size=false;this.createCanvas();this.translateToCenter()},createCanvas:function(){var d=this.opt,e=d.width,f=d.height;this.canvas=a("canvas",{id:d.injectInto+d.idSuffix,width:e,height:f,style:{position:"absolute",
top:0,left:0,width:e+"px",height:f+"px"}})},getCtx:function(){if(!this.ctx)return this.ctx=this.canvas.getContext("2d");return this.ctx},getSize:function(){if(this.size)return this.size;var d=this.canvas;return this.size={width:d.width,height:d.height}},translateToCenter:function(d){var e=this.getSize(),f=d?e.width-d.width-this.translateOffsetX*2:e.width;height=d?e.height-d.height-this.translateOffsetY*2:e.height;e=this.getCtx();d&&e.scale(1/this.scaleOffsetX,1/this.scaleOffsetY);e.translate(f/2,
height/2)},resize:function(d,e){var f=this.getSize(),g=this.canvas,h=g.style;this.size=false;g.width=d;g.height=e;h.width=d+"px";h.height=e+"px";c?this.translateToCenter():this.translateToCenter(f);this.translateOffsetX=this.translateOffsetY=0;this.scaleOffsetX=this.scaleOffsetY=1;this.clear();this.viz.resize(d,e,this)},translate:function(d,e,f){var g=this.scaleOffsetY;this.translateOffsetX+=d*this.scaleOffsetX;this.translateOffsetY+=e*g;this.getCtx().translate(d,e);!f&&this.plot()},scale:function(d,
e,f){this.scaleOffsetX*=d;this.scaleOffsetY*=e;this.getCtx().scale(d,e);!f&&this.plot()},clear:function(){var d=this.getSize(),e=this.translateOffsetX,f=this.translateOffsetY,g=this.scaleOffsetX,h=this.scaleOffsetY;this.getCtx().clearRect((-d.width/2-e)*1/g,(-d.height/2-f)*1/h,d.width*1/g,d.height*1/h)},plot:function(){this.clear();this.viz.plot(this)}});F.Background={};F.Background.Circles=new o({initialize:function(d,e){this.viz=d;this.config=i.merge({idSuffix:"-bkcanvas",levelDistance:100,numberOfCircles:6,
CanvasStyles:{},offset:0},e)},resize:function(d,e,f){this.plot(f)},plot:function(d){d=d.getCtx();var e=this.config,f=e.CanvasStyles,g;for(g in f)d[g]=f[g];g=e.numberOfCircles;e=e.levelDistance;for(f=1;f<=g;f++){d.beginPath();d.arc(0,0,e*f,0,2*Math.PI,false);d.stroke();d.closePath()}}})})();var t=function(a,b){this.theta=a;this.rho=b};$jit.Polar=t;t.prototype={getc:function(a){return this.toComplex(a)},getp:function(){return this},set:function(a){a=a.getp();this.theta=a.theta;this.rho=a.rho},setc:function(a,
b){this.rho=Math.sqrt(a*a+b*b);this.theta=Math.atan2(b,a);if(this.theta<0)this.theta+=Math.PI*2},setp:function(a,b){this.theta=a;this.rho=b},clone:function(){return new t(this.theta,this.rho)},toComplex:function(a){var b=Math.cos(this.theta)*this.rho,c=Math.sin(this.theta)*this.rho;if(a)return{x:b,y:c};return new w(b,c)},add:function(a){return new t(this.theta+a.theta,this.rho+a.rho)},scale:function(a){return new t(this.theta,this.rho*a)},equals:function(a){return this.theta==a.theta&&this.rho==a.rho},
$add:function(a){this.theta+=a.theta;this.rho+=a.rho;return this},$madd:function(a){this.theta=(this.theta+a.theta)%(Math.PI*2);this.rho+=a.rho;return this},$scale:function(a){this.rho*=a;return this},interpolate:function(a,b){var c=Math.PI,d=c*2,e=function(j){return j<0?j%d+d:j%d},f=this.theta,g=a.theta,h=Math.abs(f-g);return{theta:h==c?f>g?e(g+(f-d-g)*b):e(g-d+(f-g)*b):h>=c?f>g?e(g+(f-d-g)*b):e(g-d+(f-(g-d))*b):e(g+(f-g)*b),rho:(this.rho-a.rho)*b+a.rho}}};t.KER=new t(0,0);var w=function(a,b){this.x=
a;this.y=b};$jit.Complex=w;w.prototype={getc:function(){return this},getp:function(a){return this.toPolar(a)},set:function(a){a=a.getc(true);this.x=a.x;this.y=a.y},setc:function(a,b){this.x=a;this.y=b},setp:function(a,b){this.x=Math.cos(a)*b;this.y=Math.sin(a)*b},clone:function(){return new w(this.x,this.y)},toPolar:function(a){var b=this.norm(),c=Math.atan2(this.y,this.x);if(c<0)c+=Math.PI*2;if(a)return{theta:c,rho:b};return new t(c,b)},norm:function(){return Math.sqrt(this.squaredNorm())},squaredNorm:function(){return this.x*
this.x+this.y*this.y},add:function(a){return new w(this.x+a.x,this.y+a.y)},prod:function(a){return new w(this.x*a.x-this.y*a.y,this.y*a.x+this.x*a.y)},conjugate:function(){return new w(this.x,-this.y)},scale:function(a){return new w(this.x*a,this.y*a)},equals:function(a){return this.x==a.x&&this.y==a.y},$add:function(a){this.x+=a.x;this.y+=a.y;return this},$prod:function(a){var b=this.x,c=this.y;this.x=b*a.x-c*a.y;this.y=c*a.x+b*a.y;return this},$conjugate:function(){this.y=-this.y;return this},$scale:function(a){this.x*=
a;this.y*=a;return this},$div:function(a){var b=this.x,c=this.y,d=a.squaredNorm();this.x=b*a.x+c*a.y;this.y=c*a.x-b*a.y;return this.$scale(1/d)}};w.KER=new w(0,0);$jit.Graph=new o({initialize:function(a,b,c,d){this.Node=b;this.Edge=c;this.Label=d;this.opt=i.merge({complex:false,Node:{}},a||{});this.nodes={};this.edges={};var e=this;this.nodeList={};for(var f in O)e.nodeList[f]=function(g){return function(){var h=Array.prototype.slice.call(arguments);e.eachNode(function(j){j[g].apply(j,h)})}}(f)},
getNode:function(a){if(this.hasNode(a))return this.nodes[a];return false},getByName:function(a){for(var b in this.nodes){var c=this.nodes[b];if(c.name==a)return c}return false},getAdjacence:function(a,b){if(a in this.edges)return this.edges[a][b];return false},addNode:function(a){if(!this.nodes[a.id]){var b=this.edges[a.id]={};this.nodes[a.id]=new q.Node(i.extend({id:a.id,name:a.name,data:i.merge(a.data||{},{}),adjacencies:b},this.opt.Node),this.opt.complex,this.Node,this.Edge,this.Label)}return this.nodes[a.id]},
addAdjacence:function(a,b,c){this.hasNode(a.id)||this.addNode(a);this.hasNode(b.id)||this.addNode(b);a=this.nodes[a.id];b=this.nodes[b.id];if(!a.adjacentTo(b)){var d=this.edges[a.id]=this.edges[a.id]||{},e=this.edges[b.id]=this.edges[b.id]||{};d[b.id]=e[a.id]=new q.Adjacence(a,b,c,this.Edge,this.Label);return d[b.id]}return this.edges[a.id][b.id]},removeNode:function(a){if(this.hasNode(a)){delete this.nodes[a];var b=this.edges[a],c;for(c in b)delete this.edges[c][a];delete this.edges[a]}},removeAdjacence:function(a,
b){delete this.edges[a][b];delete this.edges[b][a]},hasNode:function(a){return a in this.nodes},empty:function(){this.nodes={};this.edges={}}});var q=$jit.Graph,O;(function(){var a=function(d,e,f,g,h){var j;f=f||"current";d="$"+(d?d+"-":"");if(f=="current")j=this.data;else if(f=="start")j=this.startData;else if(f=="end")j=this.endData;d=d+e;if(g)return j[d];if(!this.Config.overridable)return h[e]||0;return d in j?j[d]:d in this.data?this.data[d]:h[e]||0},b=function(d,e,f,g){g=g||"current";d="$"+(d?
d+"-":"");var h;if(g=="current")h=this.data;else if(g=="start")h=this.startData;else if(g=="end")h=this.endData;h[d+e]=f},c=function(d,e){d="$"+(d?d+"-":"");var f=this;i.each(e,function(g){g=d+g;delete f.data[g];delete f.endData[g];delete f.startData[g]})};O={getData:function(d,e,f){return a.call(this,"",d,e,f,this.Config)},setData:function(d,e,f){b.call(this,"",d,e,f)},setDataset:function(d,e){d=i.splat(d);for(var f in e)for(var g=0,h=i.splat(e[f]),j=d.length;g<j;g++)this.setData(f,h[g],d[g])},removeData:function(){c.call(this,
"",Array.prototype.slice.call(arguments))},getCanvasStyle:function(d,e,f){return a.call(this,"canvas",d,e,f,this.Config.CanvasStyles)},setCanvasStyle:function(d,e,f){b.call(this,"canvas",d,e,f)},setCanvasStyles:function(d,e){d=i.splat(d);for(var f in e)for(var g=0,h=i.splat(e[f]),j=d.length;g<j;g++)this.setCanvasStyle(f,h[g],d[g])},removeCanvasStyle:function(){c.call(this,"canvas",Array.prototype.slice.call(arguments))},getLabelData:function(d,e,f){return a.call(this,"label",d,e,f,this.Label)},setLabelData:function(d,
e,f){b.call(this,"label",d,e,f)},setLabelDataset:function(d,e){d=i.splat(d);for(var f in e)for(var g=0,h=i.splat(e[f]),j=d.length;g<j;g++)this.setLabelData(f,h[g],d[g])},removeLabelData:function(){c.call(this,"label",Array.prototype.slice.call(arguments))}}})();q.Node=new o({initialize:function(a,b,c,d,e){b={id:"",name:"",data:{},startData:{},endData:{},adjacencies:{},selected:false,drawn:false,exist:false,angleSpan:{begin:0,end:0},pos:b&&new w(0,0)||new t(0,0),startPos:b&&new w(0,0)||new t(0,0),
endPos:b&&new w(0,0)||new t(0,0)};i.extend(this,i.extend(b,a));this.Config=this.Node=c;this.Edge=d;this.Label=e},adjacentTo:function(a){return a.id in this.adjacencies},getAdjacency:function(a){return this.adjacencies[a]},getPos:function(a){a=a||"current";if(a=="current")return this.pos;else if(a=="end")return this.endPos;else if(a=="start")return this.startPos},setPos:function(a,b){b=b||"current";var c;if(b=="current")c=this.pos;else if(b=="end")c=this.endPos;else if(b=="start")c=this.startPos;c.set(a)}});
q.Node.implement(O);q.Adjacence=new o({initialize:function(a,b,c,d,e){this.nodeFrom=a;this.nodeTo=b;this.data=c||{};this.startData={};this.endData={};this.Config=this.Edge=d;this.Label=e}});q.Adjacence.implement(O);q.Util={filter:function(a){if(!a||i.type(a)!="string")return function(){return true};var b=a.split(" ");return function(c){for(var d=0;d<b.length;d++)if(c[b[d]])return false;return true}},getNode:function(a,b){return a.nodes[b]},eachNode:function(a,b,c){c=this.filter(c);for(var d in a.nodes)c(a.nodes[d])&&
b(a.nodes[d])},eachAdjacency:function(a,b,c){var d=a.adjacencies;c=this.filter(c);for(var e in d){var f=d[e];if(c(f)){if(f.nodeFrom!=a){var g=f.nodeFrom;f.nodeFrom=f.nodeTo;f.nodeTo=g}b(f,e)}}},computeLevels:function(a,b,c,d){c=c||0;var e=this.filter(d);this.eachNode(a,function(h){h._flag=false;h._depth=-1},d);a=a.getNode(b);a._depth=c;for(var f=[a];f.length!=0;){var g=f.pop();g._flag=true;this.eachAdjacency(g,function(h){h=h.nodeTo;if(h._flag==false&&e(h)){if(h._depth<0)h._depth=g._depth+1+c;f.unshift(h)}},
d)}},eachBFS:function(a,b,c,d){var e=this.filter(d);this.clean(a);for(var f=[a.getNode(b)];f.length!=0;){a=f.pop();a._flag=true;c(a,a._depth);this.eachAdjacency(a,function(g){g=g.nodeTo;if(g._flag==false&&e(g)){g._flag=true;f.unshift(g)}},d)}},eachLevel:function(a,b,c,d,e){var f=a._depth,g=this.filter(e),h=this;c=c===false?Number.MAX_VALUE-f:c;(function j(k,l,m){var n=k._depth;n>=l&&n<=m&&g(k)&&d(k,n);n<m&&h.eachAdjacency(k,function(p){p=p.nodeTo;p._depth>n&&j(p,l,m)})})(a,b+f,c+f)},eachSubgraph:function(a,
b,c){this.eachLevel(a,0,false,b,c)},eachSubnode:function(a,b,c){this.eachLevel(a,1,1,b,c)},anySubnode:function(a,b,c){var d=false;b=b||i.lambda(true);var e=i.type(b)=="string"?function(f){return f[b]}:b;this.eachSubnode(a,function(f){if(e(f))d=true},c);return d},getSubnodes:function(a,b,c){var d=[];b=b||0;var e;if(i.type(b)=="array"){e=b[0];b=b[1]}else{e=b;b=Number.MAX_VALUE-a._depth}this.eachLevel(a,e,b,function(f){d.push(f)},c);return d},getParents:function(a){var b=[];this.eachAdjacency(a,function(c){c=
c.nodeTo;c._depth<a._depth&&b.push(c)});return b},isDescendantOf:function(a,b){if(a.id==b)return true;for(var c=this.getParents(a),d=false,e=0;!d&&e<c.length;e++)d=d||this.isDescendantOf(c[e],b);return d},clean:function(a){this.eachNode(a,function(b){b._flag=false})},getClosestNodeToOrigin:function(a,b,c){return this.getClosestNodeToPos(a,t.KER,b,c)},getClosestNodeToPos:function(a,b,c,d){var e=null;c=c||"current";b=b&&b.getc(true)||w.KER;var f=function(g,h){var j=g.x-h.x,k=g.y-h.y;return j*j+k*k};
this.eachNode(a,function(g){e=e==null||f(g.getPos(c).getc(true),b)<f(e.getPos(c).getc(true),b)?g:e},d);return e}};i.each(["getNode","eachNode","computeLevels","eachBFS","clean","getClosestNodeToPos","getClosestNodeToOrigin"],function(a){q.prototype[a]=function(){return q.Util[a].apply(q.Util,[this].concat(Array.prototype.slice.call(arguments)))}});i.each(["eachAdjacency","eachLevel","eachSubgraph","eachSubnode","anySubnode","getSubnodes","getParents","isDescendantOf"],function(a){q.Node.prototype[a]=
function(){return q.Util[a].apply(q.Util,[this].concat(Array.prototype.slice.call(arguments)))}});q.Op={options:{type:"nothing",duration:2E3,hideLabels:true,fps:30},initialize:function(a){this.viz=a},removeNode:function(a,b){var c=this.viz,d=i.merge(this.options,c.controller,b),e=i.splat(a),f,g,h;switch(d.type){case "nothing":for(f=0;f<e.length;f++)c.graph.removeNode(e[f]);break;case "replot":this.removeNode(e,{type:"nothing"});c.labels.clearLabels();c.refresh(true);break;case "fade:seq":case "fade":g=
this;for(f=0;f<e.length;f++){h=c.graph.getNode(e[f]);h.setData("alpha",0,"end")}c.fx.animate(i.merge(d,{modes:["node-property:alpha"],onComplete:function(){g.removeNode(e,{type:"nothing"});c.labels.clearLabels();c.reposition();c.fx.animate(i.merge(d,{modes:["linear"]}))}}));break;case "fade:con":g=this;for(f=0;f<e.length;f++){h=c.graph.getNode(e[f]);h.setData("alpha",0,"end");h.ignore=true}c.reposition();c.fx.animate(i.merge(d,{modes:["node-property:alpha","linear"],onComplete:function(){g.removeNode(e,
{type:"nothing"})}}));break;case "iter":g=this;c.fx.sequence({condition:function(){return e.length!=0},step:function(){g.removeNode(e.shift(),{type:"nothing"});c.labels.clearLabels()},onComplete:function(){d.onComplete()},duration:Math.ceil(d.duration/e.length)});break;default:this.doError()}},removeEdge:function(a,b){var c=this.viz,d=i.merge(this.options,c.controller,b),e=i.type(a[0])=="string"?[a]:a,f,g,h;switch(d.type){case "nothing":for(f=0;f<e.length;f++)c.graph.removeAdjacence(e[f][0],e[f][1]);
break;case "replot":this.removeEdge(e,{type:"nothing"});c.refresh(true);break;case "fade:seq":case "fade":g=this;for(f=0;f<e.length;f++)(h=c.graph.getAdjacence(e[f][0],e[f][1]))&&h.setData("alpha",0,"end");c.fx.animate(i.merge(d,{modes:["edge-property:alpha"],onComplete:function(){g.removeEdge(e,{type:"nothing"});c.reposition();c.fx.animate(i.merge(d,{modes:["linear"]}))}}));break;case "fade:con":g=this;for(f=0;f<e.length;f++)if(h=c.graph.getAdjacence(e[f][0],e[f][1])){h.setData("alpha",0,"end");
h.ignore=true}c.reposition();c.fx.animate(i.merge(d,{modes:["edge-property:alpha","linear"],onComplete:function(){g.removeEdge(e,{type:"nothing"})}}));break;case "iter":g=this;c.fx.sequence({condition:function(){return e.length!=0},step:function(){g.removeEdge(e.shift(),{type:"nothing"});c.labels.clearLabels()},onComplete:function(){d.onComplete()},duration:Math.ceil(d.duration/e.length)});break;default:this.doError()}},sum:function(a,b){var c=this.viz,d=i.merge(this.options,c.controller,b),e=c.root,
f;c.root=b.id||c.root;switch(d.type){case "nothing":f=c.construct(a);f.eachNode(function(h){h.eachAdjacency(function(j){c.graph.addAdjacence(j.nodeFrom,j.nodeTo,j.data)})});break;case "replot":c.refresh(true);this.sum(a,{type:"nothing"});c.refresh(true);break;case "fade:seq":case "fade":case "fade:con":that=this;f=c.construct(a);var g=!this.preprocessSum(f)?["node-property:alpha"]:["node-property:alpha","edge-property:alpha"];c.reposition();if(d.type!="fade:con")c.fx.animate(i.merge(d,{modes:["linear"],
onComplete:function(){c.fx.animate(i.merge(d,{modes:g,onComplete:function(){d.onComplete()}}))}}));else{c.graph.eachNode(function(h){if(h.id!=e&&h.pos.getp().equals(t.KER)){h.pos.set(h.endPos);h.startPos.set(h.endPos)}});c.fx.animate(i.merge(d,{modes:["linear"].concat(g)}))}break;default:this.doError()}},morph:function(a,b,c){var d=this.viz,e=i.merge(this.options,d.controller,b),f=d.root,g;d.root=b.id||d.root;switch(e.type){case "nothing":g=d.construct(a);g.eachNode(function(k){var l=d.graph.hasNode(k.id);
k.eachAdjacency(function(n){var p=!!d.graph.getAdjacence(n.nodeFrom.id,n.nodeTo.id);d.graph.addAdjacence(n.nodeFrom,n.nodeTo,n.data);if(p){p=d.graph.getAdjacence(n.nodeFrom.id,n.nodeTo.id);for(var r in n.data||{})p.data[r]=n.data[r]}});if(l){l=d.graph.getNode(k.id);for(var m in k.data||{})l.data[m]=k.data[m]}});d.graph.eachNode(function(k){k.eachAdjacency(function(l){g.getAdjacence(l.nodeFrom.id,l.nodeTo.id)||d.graph.removeAdjacence(l.nodeFrom.id,l.nodeTo.id)});g.hasNode(k.id)||d.graph.removeNode(k.id)});
break;case "replot":d.labels.clearLabels(true);this.morph(a,{type:"nothing"});d.refresh(true);d.refresh(true);break;case "fade:seq":case "fade":case "fade:con":that=this;g=d.construct(a);var h=c&&"node-property"in c&&i.map(i.splat(c["node-property"]),function(k){return"$"+k});d.graph.eachNode(function(k){var l=g.getNode(k.id);if(l){l=l.data;for(var m in l)if(h&&i.indexOf(h,m)>-1)k.endData[m]=l[m];else k.data[m]=l[m]}else{k.setData("alpha",1);k.setData("alpha",1,"start");k.setData("alpha",0,"end");
k.ignore=true}});d.graph.eachNode(function(k){k.ignore||k.eachAdjacency(function(l){if(!(l.nodeFrom.ignore||l.nodeTo.ignore)){var m=g.getNode(l.nodeFrom.id);l=g.getNode(l.nodeTo.id);if(!m.adjacentTo(l)){l=d.graph.getAdjacence(m.id,l.id);j=true;l.setData("alpha",1);l.setData("alpha",1,"start");l.setData("alpha",0,"end")}}})});var j=this.preprocessSum(g);a=!j?["node-property:alpha"]:["node-property:alpha","edge-property:alpha"];a[0]+=c&&"node-property"in c?":"+i.splat(c["node-property"]).join(":"):
"";a[1]=(a[1]||"edge-property:alpha")+(c&&"edge-property"in c?":"+i.splat(c["edge-property"]).join(":"):"");c&&"label-property"in c&&a.push("label-property:"+i.splat(c["label-property"]).join(":"));d.reposition();d.graph.eachNode(function(k){if(k.id!=f&&k.pos.getp().equals(t.KER)){k.pos.set(k.endPos);k.startPos.set(k.endPos)}});d.fx.animate(i.merge(e,{modes:["linear"].concat(a),onComplete:function(){d.graph.eachNode(function(k){k.ignore&&d.graph.removeNode(k.id)});d.graph.eachNode(function(k){k.eachAdjacency(function(l){l.ignore&&
d.graph.removeAdjacence(l.nodeFrom.id,l.nodeTo.id)})});e.onComplete()}}))}},contract:function(a,b){var c=this.viz;if(!(a.collapsed||!a.anySubnode(i.lambda(true)))){b=i.merge(this.options,c.config,b||{},{modes:["node-property:alpha:span","linear"]});a.collapsed=true;(function d(e){e.eachSubnode(function(f){f.ignore=true;f.setData("alpha",0,b.type=="animate"?"end":"current");d(f)})})(a);if(b.type=="animate"){c.compute("end");c.rotated&&c.rotate(c.rotated,"none",{property:"end"});(function d(e){e.eachSubnode(function(f){f.setPos(a.getPos("end"),
"end");d(f)})})(a);c.fx.animate(b)}else b.type=="replot"&&c.refresh()}},expand:function(a,b){if("collapsed"in a){var c=this.viz;b=i.merge(this.options,c.config,b||{},{modes:["node-property:alpha:span","linear"]});delete a.collapsed;(function d(e){e.eachSubnode(function(f){delete f.ignore;f.setData("alpha",1,b.type=="animate"?"end":"current");d(f)})})(a);if(b.type=="animate"){c.compute("end");c.rotated&&c.rotate(c.rotated,"none",{property:"end"});c.fx.animate(b)}else b.type=="replot"&&c.refresh()}},
preprocessSum:function(a){var b=this.viz;a.eachNode(function(d){if(!b.graph.hasNode(d.id)){b.graph.addNode(d);d=b.graph.getNode(d.id);d.setData("alpha",0);d.setData("alpha",0,"start");d.setData("alpha",1,"end")}});var c=false;a.eachNode(function(d){d.eachAdjacency(function(e){var f=b.graph.getNode(e.nodeFrom.id),g=b.graph.getNode(e.nodeTo.id);if(!f.adjacentTo(g)){e=b.graph.addAdjacence(f,g,e.data);if(f.startAlpha==f.endAlpha&&g.startAlpha==g.endAlpha){c=true;e.setData("alpha",0);e.setData("alpha",
0,"start");e.setData("alpha",1,"end")}}})});return c}};var Q={none:{render:i.empty,contains:i.lambda(false)},circle:{render:function(a,b,c,d){d=d.getCtx();d.beginPath();d.arc(b.x,b.y,c,0,Math.PI*2,true);d.closePath();d[a]()},contains:function(a,b,c){var d=a.x-b.x;a=a.y-b.y;return d*d+a*a<=c*c}},ellipse:{render:function(a,b,c,d,e){e=e.getCtx();d/=2;c/=2;e.save();e.scale(c/d,d/c);e.beginPath();e.arc(b.x*(d/c),b.y*(c/d),d,0,Math.PI*2,true);e.closePath();e[a]();e.restore()},contains:function(a,b,c,d){c/=
2;d/=2;c=(c+d)/2;d=a.x-b.x;a=a.y-b.y;return d*d+a*a<=c*c}},square:{render:function(a,b,c,d){d.getCtx()[a+"Rect"](b.x-c,b.y-c,2*c,2*c)},contains:function(a,b,c){return Math.abs(b.x-a.x)<=c&&Math.abs(b.y-a.y)<=c}},rectangle:{render:function(a,b,c,d,e){e.getCtx()[a+"Rect"](b.x-c/2,b.y-d/2,c,d)},contains:function(a,b,c,d){return Math.abs(b.x-a.x)<=c/2&&Math.abs(b.y-a.y)<=d/2}},triangle:{render:function(a,b,c,d){d=d.getCtx();var e=b.x,f=b.y-c,g=e-c;b=b.y+c;c=e+c;d.beginPath();d.moveTo(e,f);d.lineTo(g,
b);d.lineTo(c,b);d.closePath();d[a]()},contains:function(a,b,c){return Q.circle.contains(a,b,c)}},star:{render:function(a,b,c,d){d=d.getCtx();var e=Math.PI/5;d.save();d.translate(b.x,b.y);d.beginPath();d.moveTo(c,0);for(b=0;b<9;b++){d.rotate(e);b%2==0?d.lineTo(c/0.525731*0.200811,0):d.lineTo(c,0)}d.closePath();d[a]();d.restore()},contains:function(a,b,c){return Q.circle.contains(a,b,c)}}},R={line:{render:function(a,b,c){c=c.getCtx();c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke()},contains:function(a,
b,c,d){var e=Math.min,f=Math.max,g=e(a.x,b.x),h=f(a.x,b.x);e=e(a.y,b.y);f=f(a.y,b.y);if(c.x>=g&&c.x<=h&&c.y>=e&&c.y<=f){if(Math.abs(b.x-a.x)<=d)return true;return Math.abs((b.y-a.y)/(b.x-a.x)*(c.x-a.x)+a.y-c.y)<=d}return false}},arrow:{render:function(a,b,c,d,e){e=e.getCtx();if(d){d=a;a=b;b=d}d=new w(b.x-a.x,b.y-a.y);d.$scale(c/d.norm());c=new w(b.x-d.x,b.y-d.y);var f=new w(-d.y/2,d.x/2);d=c.add(f);c=c.$add(f.$scale(-1));e.beginPath();e.moveTo(a.x,a.y);e.lineTo(b.x,b.y);e.stroke();e.beginPath();e.moveTo(d.x,
d.y);e.lineTo(c.x,c.y);e.lineTo(b.x,b.y);e.closePath();e.fill()},contains:function(a,b,c,d){return R.line.contains(a,b,c,d)}},hyperline:{render:function(a,b,c,d){function e(g,h){return g<h?g+Math.PI>h?false:true:h+Math.PI>g?true:false}d=d.getCtx();var f=function(g,h){var j=g.x*h.y-g.y*h.x,k=g.squaredNorm(),l=h.squaredNorm();if(j==0)return{x:0,y:0,ratio:-1};var m=(g.y*l-h.y*k+g.y-h.y)/j;j=(h.x*k-g.x*l+h.x-g.x)/j;k=(m*m+j*j)/4-1;if(k<0)return{x:0,y:0,ratio:-1};k=Math.sqrt(k);return{x:-m/2,y:-j/2,ratio:k>
1E3?-1:k,a:m,b:j}}(a,b);if(f.a>1E3||f.b>1E3||f.ratio<0){d.beginPath();d.moveTo(a.x*c,a.y*c);d.lineTo(b.x*c,b.y*c)}else{b=Math.atan2(b.y-f.y,b.x-f.x);a=Math.atan2(a.y-f.y,a.x-f.x);e=e(b,a);d.beginPath();d.arc(f.x*c,f.y*c,f.ratio*c,b,a,e)}d.stroke()},contains:i.lambda(false)}};q.Plot={initialize:function(a,b){this.viz=a;this.config=a.config;this.node=a.config.Node;this.edge=a.config.Edge;this.animation=new P;this.nodeTypes=new b.Plot.NodeTypes;this.edgeTypes=new b.Plot.EdgeTypes;this.labels=a.labels},
nodeHelper:Q,edgeHelper:R,Interpolator:{map:{border:"color",color:"color",width:"number",height:"number",dim:"number",alpha:"number",lineWidth:"number",angularWidth:"number",span:"number",valueArray:"array-number",dimArray:"array-number"},canvas:{globalAlpha:"number",fillStyle:"color",strokeStyle:"color",lineWidth:"number",shadowBlur:"number",shadowColor:"color",shadowOffsetX:"number",shadowOffsetY:"number",miterLimit:"number"},label:{size:"number",color:"color"},compute:function(a,b,c){return a+
(b-a)*c},moebius:function(a,b,c,d){b=d.scale(-c);if(b.norm()<1){c=b.x;d=b.y;var e=a.startPos.getc().moebiusTransformation(b);a.pos.setc(e.x,e.y);b.x=c;b.y=d}},linear:function(a,b,c){b=a.startPos.getc(true);var d=a.endPos.getc(true);a.pos.setc(this.compute(b.x,d.x,c),this.compute(b.y,d.y,c))},polar:function(a,b,c){b=a.startPos.getp(true);c=a.endPos.getp().interpolate(b,c);a.pos.setp(c.theta,c.rho)},number:function(a,b,c,d,e){var f=a[d](b,"start");d=a[d](b,"end");a[e](b,this.compute(f,d,c))},color:function(a,
b,c,d,e){var f=i.hexToRgb(a[d](b,"start"));d=i.hexToRgb(a[d](b,"end"));var g=this.compute;c=i.rgbToHex([parseInt(g(f[0],d[0],c)),parseInt(g(f[1],d[1],c)),parseInt(g(f[2],d[2],c))]);a[e](b,c)},"array-number":function(a,b,c,d,e){var f=a[d](b,"start");d=a[d](b,"end");for(var g=[],h=0,j=f.length;h<j;h++){var k=f[h],l=d[h];if(k.length){for(var m=0,n=k.length,p=[];m<n;m++)p.push(this.compute(k[m],l[m],c));g.push(p)}else g.push(this.compute(k,l,c))}a[e](b,g)},node:function(a,b,c,d,e,f){d=this[d];if(b)for(var g=
b.length,h=0;h<g;h++){var j=b[h];this[d[j]](a,j,c,e,f)}else for(j in d)this[d[j]](a,j,c,e,f)},edge:function(a,b,c,d,e,f){a=a.adjacencies;for(var g in a)this.node(a[g],b,c,d,e,f)},"node-property":function(a,b,c){this.node(a,b,c,"map","getData","setData")},"edge-property":function(a,b,c){this.edge(a,b,c,"map","getData","setData")},"label-property":function(a,b,c){this.node(a,b,c,"label","getLabelData","setLabelData")},"node-style":function(a,b,c){this.node(a,b,c,"canvas","getCanvasStyle","setCanvasStyle")},
"edge-style":function(a,b,c){this.edge(a,b,c,"canvas","getCanvasStyle","setCanvasStyle")}},sequence:function(a){var b=this;a=i.merge({condition:i.lambda(false),step:i.empty,onComplete:i.empty,duration:200},a||{});var c=setInterval(function(){if(a.condition())a.step();else{clearInterval(c);a.onComplete()}b.viz.refresh(true)},a.duration)},prepare:function(a){var b=this.viz.graph,c={"node-property":{getter:"getData",setter:"setData"},"edge-property":{getter:"getData",setter:"setData"},"node-style":{getter:"getCanvasStyle",
setter:"setCanvasStyle"},"edge-style":{getter:"getCanvasStyle",setter:"setCanvasStyle"}},d={};if(i.type(a)=="array")for(var e=0,f=a.length;e<f;e++){var g=a[e].split(":");d[g.shift()]=g}else for(e in a)if(e=="position")d[a.position]=[];else d[e]=i.splat(a[e]);b.eachNode(function(h){h.startPos.set(h.pos);i.each(["node-property","node-style"],function(j){if(j in d)for(var k=d[j],l=0,m=k.length;l<m;l++)h[c[j].setter](k[l],h[c[j].getter](k[l]),"start")});i.each(["edge-property","edge-style"],function(j){if(j in
d){var k=d[j];h.eachAdjacency(function(l){for(var m=0,n=k.length;m<n;m++)l[c[j].setter](k[m],l[c[j].getter](k[m]),"start")})}})});return d},animate:function(a,b){a=i.merge(this.viz.config,a||{});var c=this,d=this.viz.graph,e=this.Interpolator,f=a.type==="nodefx"?this.nodeFxAnimation:this.animation,g=this.prepare(a.modes);a.hideLabels&&this.labels.hideLabels(true);f.setOptions(i.merge(a,{$animating:false,compute:function(h){d.eachNode(function(j){for(var k in g)e[k](j,g[k],h,b)});c.plot(a,this.$animating,
h);this.$animating=true},complete:function(){a.hideLabels&&c.labels.hideLabels(false);c.plot(a);a.onComplete();a.onAfterCompute()}})).start()},nodeFx:function(a){var b=this.viz,c=b.graph,d=this.nodeFxAnimation,e=i.merge(this.viz.config,{elements:{id:false,properties:{}},reposition:false});a=i.merge(e,a||{},{onBeforeCompute:i.empty,onAfterCompute:i.empty});d.stopTimer();var f=a.elements.properties;if(a.elements.id){d=i.splat(a.elements.id);i.each(d,function(h){if(h=c.getNode(h))for(var j in f)h.setData(j,
f[j],"end")})}else c.eachNode(function(h){for(var j in f)h.setData(j,f[j],"end")});d=[];for(var g in f)d.push(g);g=["node-property:"+d.join(":")];if(a.reposition){g.push("linear");b.compute("end")}this.animate(i.merge(a,{modes:g,type:"nodefx"}))},plot:function(a,b){var c=this.viz,d=c.graph,e=c.canvas;c=c.root;var f=this,g=e.getCtx(),h=Math.min;a=a||this.viz.controller;a.clearCanvas&&e.clear();if(c=d.getNode(c)){var j=!!c.visited;d.eachNode(function(k){var l=k.getData("alpha");k.eachAdjacency(function(m){var n=
m.nodeTo;if(!!n.visited===j&&k.drawn&&n.drawn){!b&&a.onBeforePlotLine(m);g.save();g.globalAlpha=h(l,n.getData("alpha"),m.getData("alpha"));f.plotLine(m,e,b);g.restore();!b&&a.onAfterPlotLine(m)}});g.save();if(k.drawn){!b&&a.onBeforePlotNode(k);f.plotNode(k,e,b);!b&&a.onAfterPlotNode(k)}if(!f.labelsHidden&&a.withLabels)k.drawn&&l>=0.95?f.labels.plotLabel(e,k,a):f.labels.hideLabel(k,false);g.restore();k.visited=!j})}},plotTree:function(a,b,c){var d=this,e=this.viz.canvas,f=e.getCtx(),g=a.getData("alpha");
a.eachSubnode(function(h){if(b.plotSubtree(a,h)&&h.exist&&h.drawn){var j=a.getAdjacency(h.id);!c&&b.onBeforePlotLine(j);f.globalAlpha=Math.min(g,h.getData("alpha"));d.plotLine(j,e,c);!c&&b.onAfterPlotLine(j);d.plotTree(h,b,c)}});if(a.drawn){!c&&b.onBeforePlotNode(a);this.plotNode(a,e,c);!c&&b.onAfterPlotNode(a);!b.hideLabels&&b.withLabels&&g>=0.95?this.labels.plotLabel(e,a,b):this.labels.hideLabel(a,false)}else this.labels.hideLabel(a,true)},plotNode:function(a,b,c){var d=a.getData("type"),e=this.node.CanvasStyles;
if(d!="none"){var f=a.getData("lineWidth"),g=a.getData("color"),h=a.getData("alpha"),j=b.getCtx();j.lineWidth=f;j.fillStyle=j.strokeStyle=g;j.globalAlpha=h;for(var k in e)j[k]=a.getCanvasStyle(k);this.nodeTypes[d].render.call(this,a,b,c)}},plotLine:function(a,b,c){var d=a.getData("type"),e=this.edge.CanvasStyles;if(d!="none"){var f=a.getData("lineWidth"),g=a.getData("color"),h=b.getCtx();h.lineWidth=f;h.fillStyle=h.strokeStyle=g;for(var j in e)h[j]=a.getCanvasStyle(j);this.edgeTypes[d].render.call(this,
a,b,c)}}};q.Label={};q.Label.Native=new o({plotLabel:function(a,b,c){var d=a.getCtx();b.pos.getc(true);d.font=b.getLabelData("style")+" "+b.getLabelData("size")+"px "+b.getLabelData("family");d.textAlign=b.getLabelData("textAlign");d.fillStyle=d.strokeStyle=b.getLabelData("color");d.textBaseline=b.getLabelData("textBaseline");this.renderLabel(a,b,c)},renderLabel:function(a,b){var c=a.getCtx(),d=b.pos.getc(true);c.fillText(b.name,d.x,d.y+b.getData("height")/2)},hideLabel:i.empty,hideLabels:i.empty});
q.Label.DOM=new o({labelsHidden:false,labelContainer:false,labels:{},getLabelContainer:function(){return this.labelContainer?this.labelContainer:this.labelContainer=document.getElementById(this.viz.config.labelContainer)},getLabel:function(a){return a in this.labels&&this.labels[a]!=null?this.labels[a]:this.labels[a]=document.getElementById(a)},hideLabels:function(a){this.getLabelContainer().style.display=a?"none":"";this.labelsHidden=a},clearLabels:function(a){for(var b in this.labels)if(a||!this.viz.graph.hasNode(b)){this.disposeLabel(b);
delete this.labels[b]}},disposeLabel:function(a){(a=this.getLabel(a))&&a.parentNode&&a.parentNode.removeChild(a)},hideLabel:function(a,b){a=i.splat(a);var c=b?"":"none",d=this;i.each(a,function(e){if(e=d.getLabel(e.id))e.style.display=c})},fitsInCanvas:function(a,b){var c=b.getSize();if(a.x>=c.width||a.x<0||a.y>=c.height||a.y<0)return false;return true}});q.Label.HTML=new o({Implements:q.Label.DOM,plotLabel:function(a,b,c){a=b.id;var d=this.getLabel(a);if(!d&&!(d=document.getElementById(a))){d=document.createElement("div");
var e=this.getLabelContainer();d.id=a;d.className="node";d.style.position="absolute";c.onCreateLabel(d,b);e.appendChild(d);this.labels[b.id]=d}this.placeLabel(d,b,c)}});q.Label.SVG=new o({Implements:q.Label.DOM,plotLabel:function(a,b,c){a=b.id;var d=this.getLabel(a);if(!d&&!(d=document.getElementById(a))){d=document.createElementNS("http://www.w3.org/2000/svg","svg:text");var e=document.createElementNS("http://www.w3.org/2000/svg","svg:tspan");d.appendChild(e);e=this.getLabelContainer();d.setAttribute("id",
a);d.setAttribute("class","node");e.appendChild(d);c.onCreateLabel(d,b);this.labels[b.id]=d}this.placeLabel(d,b,c)}});E={construct:function(a){var b=i.type(a)=="array",c=new q(this.graphOptions,this.config.Node,this.config.Edge,this.config.Label);b?function(d,e){for(var f=function(p){for(var r=0,A=e.length;r<A;r++)if(e[r].id==p)return e[r];return d.addNode({id:p,name:p})},g=0,h=e.length;g<h;g++){d.addNode(e[g]);var j=e[g].adjacencies;if(j)for(var k=0,l=j.length;k<l;k++){var m=j[k],n={};if(typeof j[k]!=
"string"){n=i.merge(m.data,{});m=m.nodeTo}d.addAdjacence(e[g],f(m),n)}}}(c,a):function(d,e){d.addNode(e);if(e.children)for(var f=0,g=e.children;f<g.length;f++){d.addAdjacence(e,g[f]);arguments.callee(d,g[f])}}(c,a);return c},loadJSON:function(a,b){this.json=a;this.labels&&this.labels.clearLabels&&this.labels.clearLabels(true);this.graph=this.construct(a);this.root=i.type(a)!="array"?a.id:a[b?b:0].id},toJSON:function(a){a=a||"tree";if(a=="tree"){var b={};b=function d(e){var f={};f.id=e.id;f.name=e.name;
f.data=e.data;var g=[];e.eachSubnode(function(h){g.push(d(h))});f.children=g;return f}(this.graph.getNode(this.root))}else{b=[];var c=!!this.graph.getNode(this.root).visited;this.graph.eachNode(function(d){var e={};e.id=d.id;e.name=d.name;e.data=d.data;var f=[];d.eachAdjacency(function(g){var h=g.nodeTo;if(!!h.visited===c){var j={};j.nodeTo=h.id;j.data=g.data;f.push(j)}});e.adjacencies=f;b.push(e);d.visited=!c})}return b}};v=$jit.Layouts={};var T={label:null,compute:function(a,b,c){this.initializeLabel(c);
var d=this.label,e=d.style;a.eachNode(function(f){var g=f.getData("autoWidth"),h=f.getData("autoHeight");if(g||h){delete f.data.$width;delete f.data.$height;delete f.data.$dim;var j=f.getData("width"),k=f.getData("height");e.width=g?"auto":j+"px";e.height=h?"auto":k+"px";d.innerHTML=f.name;g=d.offsetWidth;h=d.offsetHeight;j=f.getData("type");if(i.indexOf(["circle","square","triangle","star"],j)===-1){f.setData("width",g);f.setData("height",h)}else{g=g>h?g:h;f.setData("width",g);f.setData("height",
g);f.setData("dim",g)}}})},initializeLabel:function(a){if(!this.label){this.label=document.createElement("div");document.body.appendChild(this.label)}this.setLabelStyles(a)},setLabelStyles:function(){i.extend(this.label.style,{visibility:"hidden",position:"absolute",width:"auto",height:"auto"});this.label.className="jit-autoadjust-label"}};v.Radial=new o({compute:function(a){a=i.splat(a||["current","start","end"]);T.compute(this.graph,a,this.config);this.graph.computeLevels(this.root,0,"ignore");
var b=this.createLevelDistanceFunc();this.computeAngularWidths(a);this.computePositions(a,b)},computePositions:function(a,b){for(var c=this.graph,d=c.getNode(this.root),e=this.parent,f=0,g=a.length;f<g;f++){var h=a[f];d.setPos(new t(0,0),h);d.setData("span",Math.PI*2,h)}d.angleSpan={begin:0,end:2*Math.PI};c.eachBFS(this.root,function(j){var k=j.angleSpan.end-j.angleSpan.begin,l=j.angleSpan.begin,m=b(j),n=0,p=[],r={};j.eachSubnode(function(y){n+=y._treeAngularWidth;for(var H=0,I=a.length;H<I;H++){var C=
a[H],J=y.getData("dim",C);r[C]=C in r?J>r[C]?J:r[C]:J}p.push(y)},"ignore");e&&e.id==j.id&&p.length>0&&p[0].dist&&p.sort(function(y,H){return(y.dist>=H.dist)-(y.dist<=H.dist)});j=0;for(var A=p.length;j<A;j++){var u=p[j];if(!u._flag){for(var z=u._treeAngularWidth/n*k,K=l+z/2,D=0,G=a.length;D<G;D++){var L=a[D];u.setPos(new t(K,m),L);u.setData("span",z,L);u.setData("dim-quotient",u.getData("dim",L)/r[L],L)}u.angleSpan={begin:l,end:l+z};l+=z}}},"ignore")},setAngularWidthForNodes:function(a){this.graph.eachBFS(this.root,
function(b,c){var d=b.getData("angularWidth",a[0])||5;b._angularWidth=d/c},"ignore")},setSubtreesAngularWidth:function(){var a=this;this.graph.eachNode(function(b){a.setSubtreeAngularWidth(b)},"ignore")},setSubtreeAngularWidth:function(a){var b=this,c=a._angularWidth,d=0;a.eachSubnode(function(e){b.setSubtreeAngularWidth(e);d+=e._treeAngularWidth},"ignore");a._treeAngularWidth=Math.max(c,d)},computeAngularWidths:function(a){this.setAngularWidthForNodes(a);this.setSubtreesAngularWidth()}});$jit.Sunburst=
new o({Implements:[E,B,v.Radial],initialize:function(a){var b=$jit.Sunburst;a=this.controller=this.config=i.merge(x("Canvas","Node","Edge","Fx","Tips","NodeStyles","Events","Navigation","Controller","Label"),{interpolation:"linear",levelDistance:100,Node:{type:"multipie",height:0},Edge:{type:"none"},Label:{textAlign:"start",textBaseline:"middle"}},a);if(a.useCanvas){this.canvas=a.useCanvas;this.config.labelContainer=this.canvas.id+"-label"}else{if(a.background)a.background=i.merge({type:"Circles"},
a.background);this.canvas=new F(this,a);this.config.labelContainer=(typeof a.injectInto=="string"?a.injectInto:a.injectInto.id)+"-label"}this.graphOptions={complex:false,Node:{selected:false,exist:true,drawn:true}};this.graph=new q(this.graphOptions,this.config.Node,this.config.Edge);this.labels=new b.Label[a.Label.type](this);this.fx=new b.Plot(this,b);this.op=new b.Op(this);this.rotated=this.root=this.json=null;this.busy=false;this.initializeExtras()},createLevelDistanceFunc:function(){var a=this.config.levelDistance;
return function(b){return(b._depth+1)*a}},refresh:function(){this.compute();this.plot()},reposition:function(){this.compute("end")},rotate:function(a,b,c){var d=a.getPos(c.property||"current").getp(true).theta;this.rotated=a;this.rotateAngle(-d,b,c)},rotateAngle:function(a,b,c){var d=i.merge(this.config,c||{},{modes:["polar"]}),e=c.property||(b==="animate"?"end":"current");b==="animate"&&this.fx.animation.pause();this.graph.eachNode(function(f){f=f.getPos(e);f.theta+=a;if(f.theta<0)f.theta+=Math.PI*
2});if(b=="animate")this.fx.animate(d);else if(b=="replot"){this.fx.plot();this.busy=false}},plot:function(){this.fx.plot()}});$jit.Sunburst.$extend=true;(function(a){a.Op=new o({Implements:q.Op});a.Plot=new o({Implements:q.Plot});a.Label={};a.Label.Native=new o({Implements:q.Label.Native,initialize:function(b){this.viz=b;this.label=b.config.Label;this.config=b.config},renderLabel:function(b,c){var d=c.getData("span");if(!(d<Math.PI/2&&Math.tan(d)*this.config.levelDistance*c._depth<10)){d=b.getCtx();
var e=d.measureText(c.name);if(c.id==this.viz.root)var f=-e.width/2,g=0,h=0;else{f=c.pos.clone();f.rho+=5;var j=f.getp(true);g=f.getc(true);f=g.x;g=g.y;h=Math.PI;var k=j.theta>h/2&&j.theta<3*h/2;h=k?j.theta+h:j.theta;if(k){f-=Math.abs(Math.cos(j.theta)*e.width);g+=Math.sin(j.theta)*e.width}else if(c.id==this.viz.root)f-=e.width/2}d.save();d.translate(f,g);d.rotate(h);d.fillText(c.name,0,0);d.restore()}}});a.Label.SVG=new o({Implements:q.Label.SVG,initialize:function(b){this.viz=b},placeLabel:function(b,
c,d){var e=c.pos.getc(true),f=this.viz,g=this.viz.canvas.getSize();e={x:Math.round(e.x+g.width/2),y:Math.round(e.y+g.height/2)};b.setAttribute("x",e.x);b.setAttribute("y",e.y);var h=b.getBBox();if(h){e=b.getAttribute("x");g=b.getAttribute("y");var j=c.pos.getp(true),k=Math.PI,l=j.theta>k/2&&j.theta<3*k/2;if(l){b.setAttribute("x",e-h.width);b.setAttribute("y",g-h.height)}else c.id==f.root&&b.setAttribute("x",e-h.width/2);f=l?j.theta+k:j.theta;c._depth&&b.setAttribute("transform","rotate("+f*360/(2*
k)+" "+e+" "+g+")")}d.onPlaceLabel(b,c)}});a.Label.HTML=new o({Implements:q.Label.HTML,initialize:function(b){this.viz=b},placeLabel:function(b,c,d){var e=c.pos.clone(),f=this.viz.canvas,g=c.getData("height");g=(g||c._depth==0?g:this.viz.config.levelDistance)/2;var h=f.getSize();e.rho+=g;e=e.getc(true);e={x:Math.round(e.x+h.width/2),y:Math.round(e.y+h.height/2)};g=b.style;g.left=e.x+"px";g.top=e.y+"px";g.display=this.fitsInCanvas(e,f)?"":"none";d.onPlaceLabel(b,c)}});a.Plot.NodeTypes=new o({none:{render:i.empty,
contains:i.lambda(false),anglecontains:function(b,c){var d=b.getData("span")/2,e=b.pos.theta,f=e-d;d=e+d;if(f<0)f+=Math.PI*2;e=Math.atan2(c.y,c.x);if(e<0)e+=Math.PI*2;return f>d?e>f&&e<=Math.PI*2||e<d:e>f&&e<d}},pie:{render:function(b,c){var d=b.getData("span")/2,e=b.pos.theta,f=e-d;d=e+d;e=b.pos.getp(true);var g=new t(e.rho,f),h=g.getc(true);g.theta=d;g=g.getc(true);var j=c.getCtx();j.beginPath();j.moveTo(0,0);j.lineTo(h.x,h.y);j.moveTo(0,0);j.lineTo(g.x,g.y);j.moveTo(0,0);j.arc(0,0,e.rho*b.getData("dim-quotient"),
f,d,false);j.fill()},contains:function(b,c){if(this.nodeTypes.none.anglecontains.call(this,b,c))return Math.sqrt(c.x*c.x+c.y*c.y)<=this.config.levelDistance*b._depth;return false}},multipie:{render:function(b,c){var d=b.getData("height");d=d?d:this.config.levelDistance;var e=b.getData("span")/2,f=b.pos.theta,g=f-e;e=f+e;f=b.pos.getp(true);var h=new t(f.rho,g),j=h.getc(true);h.theta=e;var k=h.getc(true);h.rho+=d;var l=h.getc(true);h.theta=g;h=h.getc(true);var m=c.getCtx();m.moveTo(0,0);m.beginPath();
m.arc(0,0,f.rho,g,e,false);m.arc(0,0,f.rho+d,e,g,true);m.moveTo(j.x,j.y);m.lineTo(h.x,h.y);m.moveTo(k.x,k.y);m.lineTo(l.x,l.y);m.fill();if(b.collapsed){m.save();m.lineWidth=2;m.moveTo(0,0);m.beginPath();m.arc(0,0,f.rho+d+5,e-0.01,g+0.01,true);m.stroke();m.restore()}},contains:function(b,c){if(this.nodeTypes.none.anglecontains.call(this,b,c)){var d=Math.sqrt(c.x*c.x+c.y*c.y),e=b.getData("height");e=e?e:this.config.levelDistance;var f=this.config.levelDistance,g=b._depth;return d>=f*g&&d<=f*g+e}return false}},
"gradient-multipie":{render:function(b,c){var d=c.getCtx(),e=b.getData("height");e=e?e:this.config.levelDistance;e=d.createRadialGradient(0,0,b.getPos().rho,0,0,b.getPos().rho+e);var f=i.hexToRgb(b.getData("color")),g=[];i.each(f,function(h){g.push(parseInt(h*0.5,10))});f=i.rgbToHex(g);e.addColorStop(0,f);e.addColorStop(1,b.getData("color"));d.fillStyle=e;this.nodeTypes.multipie.render.call(this,b,c)},contains:function(b,c){return this.nodeTypes.multipie.contains.call(this,b,c)}},"gradient-pie":{render:function(b,
c){var d=c.getCtx(),e=d.createRadialGradient(0,0,0,0,0,b.getPos().rho),f=i.hexToRgb(b.getData("color")),g=[];i.each(f,function(h){g.push(parseInt(h*0.5,10))});f=i.rgbToHex(g);e.addColorStop(1,f);e.addColorStop(0,b.getData("color"));d.fillStyle=e;this.nodeTypes.pie.render.call(this,b,c)},contains:function(b,c){return this.nodeTypes.pie.contains.call(this,b,c)}}});a.Plot.EdgeTypes=new o({none:i.empty,line:{render:function(b,c){var d=b.nodeFrom.pos.getc(true),e=b.nodeTo.pos.getc(true);this.edgeHelper.line.render(d,
e,c)},contains:function(b,c){var d=b.nodeFrom.pos.getc(true),e=b.nodeTo.pos.getc(true);return this.edgeHelper.line.contains(d,e,c,this.edge.epsilon)}},arrow:{render:function(b,c){var d=b.nodeFrom.pos.getc(true),e=b.nodeTo.pos.getc(true),f=b.getData("dim"),g=b.data.$direction;this.edgeHelper.arrow.render(d,e,f,g&&g.length>1&&g[0]!=b.nodeFrom.id,c)},contains:function(b,c){var d=b.nodeFrom.pos.getc(true),e=b.nodeTo.pos.getc(true);return this.edgeHelper.arrow.contains(d,e,c,this.edge.epsilon)}},hyperline:{render:function(b,
c){var d=b.nodeFrom.pos.getc(),e=b.nodeTo.pos.getc(),f=Math.max(d.norm(),e.norm());this.edgeHelper.hyperline.render(d.$scale(1/f),e.$scale(1/f),f,c)},contains:i.lambda(false)}})})($jit.Sunburst);$jit.Sunburst.Plot.NodeTypes.implement({"piechart-stacked":{render:function(a,b){a.pos.getp(true);var c=a.getData("dimArray"),d=a.getData("valueArray"),e=a.getData("colorArray"),f=e.length,g=a.getData("stringArray"),h=a.getData("span")/2,j=a.pos.theta,k=j-h,l=j+h;j=new t;h=b.getCtx();var m={},n=a.getData("gradient"),
p=a.getData("border"),r=a.getData("config"),A=r.showLabels,u=r.resizeLabels,z=r.Label,K=r.sliceOffset*Math.cos((k+l)/2),D=r.sliceOffset*Math.sin((k+l)/2);if(e&&c&&g){for(var G=0,L=c.length,y=0,H=0;G<L;G++){var I=c[G],C=e[G%f];if(!(I<=0)){h.fillStyle=h.strokeStyle=C;if(n&&I){var J=h.createRadialGradient(K,D,y+r.sliceOffset,K,D,y+I+r.sliceOffset),N=i.hexToRgb(C);N=i.map(N,function(U){return U*0.8>>0});N=i.rgbToHex(N);J.addColorStop(0,C);J.addColorStop(0.5,C);J.addColorStop(1,N);h.fillStyle=J}j.rho=
y+r.sliceOffset;j.theta=k;j.getc(true);j.theta=l;j.getc(true);j.rho+=I;j.getc(true);j.theta=k;j.getc(true);h.beginPath();h.arc(K,D,y+0.01,k,l,false);h.arc(K,D,y+I+0.01,l,k,true);h.fill();if(p&&p.name==g[G]){m.acum=y;m.dimValue=c[G];m.begin=k;m.end=l}y+=I||0;H+=d[G]||0}}if(p){h.save();h.globalCompositeOperation="source-over";h.lineWidth=2;h.strokeStyle=p.color;h.beginPath();h.arc(K,D,m.acum+0.01+1,m.begin,m.end,false);h.arc(K,D,m.acum+m.dimValue+0.01-1,m.end,m.begin,true);h.closePath();h.stroke();
h.restore()}if(A&&z.type=="Native"){h.save();h.fillStyle=h.strokeStyle=z.color;c=u?a.getData("normalizedDim"):1;c=z.size*c>>0;c=c<+u?+u:c;h.font=z.style+" "+c+"px "+z.family;h.textBaseline="middle";h.textAlign="center";j.rho=y+r.labelOffset+r.sliceOffset;j.theta=a.pos.theta;c=j.getc(true);h.fillText(a.name,c.x,c.y);h.restore()}}},contains:function(a,b){if(this.nodeTypes.none.anglecontains.call(this,a,b)){var c=Math.sqrt(b.x*b.x+b.y*b.y),d=this.config.levelDistance,e=a._depth,f=a.getData("config");
if(c<=d*e+f.sliceOffset){d=a.getData("dimArray");e=0;var g=d.length;for(f=f.sliceOffset;e<g;e++){var h=d[e];if(c>=f&&c<=f+h)return{name:a.getData("stringArray")[e],color:a.getData("colorArray")[e],value:a.getData("valueArray")[e],label:a.name};f+=h}}return false}return false}}});$jit.PieChart=new o({sb:null,colors:["#416D9C","#70A35E","#EBB056","#C74243","#83548B","#909291","#557EAA"],selected:{},busy:false,initialize:function(a){this.controller=this.config=i.merge(x("Canvas","PieChart","Label"),
{Label:{type:"Native"}},a);this.initializeViz()},initializeViz:function(){var a=this.config,b=this,c=a.type.split(":")[0];c=new $jit.Sunburst({injectInto:a.injectInto,useCanvas:a.useCanvas,withLabels:a.Label.type!="Native",Label:{type:a.Label.type},Node:{overridable:true,type:"piechart-"+c,width:1,height:1},Edge:{type:"none"},Tips:{enable:a.Tips.enable,type:"Native",force:true,onShow:function(f,g,h){a.Tips.onShow(f,h,g)}},Events:{enable:true,type:"Native",onClick:function(f,g,h){if(a.Events.enable){f=
g.getContains();a.Events.onClick(f,g,h)}},onMouseMove:function(f,g){if(a.hoveredColor)if(f){var h=g.getContains();b.select(f.id,h.name,h.index)}else b.select(false,false,false)}},onCreateLabel:function(f,g){var h=a.Label;if(a.showLabels){var j=f.style;j.fontSize=h.size+"px";j.fontFamily=h.family;j.color=h.color;j.textAlign="center";f.innerHTML=g.name}},onPlaceLabel:function(f,g){if(a.showLabels){var h=g.pos.getp(true),j=g.getData("dimArray"),k=g.getData("span")/2,l=g.pos.theta;h=l-k;k=l+k;l=new t;
var m=a.resizeLabels,n=a.Label;if(j){for(var p=0,r=j.length,A=0;p<r;p++)A+=j[p];j=m?g.getData("normalizedDim"):1;j=n.size*j>>0;j=j<+m?+m:j;f.style.fontSize=j+"px";l.rho=A+a.labelOffset+a.sliceOffset;l.theta=(h+k)/2;h=l.getc(true);j=b.canvas.getSize();h={x:Math.round(h.x+j.width/2),y:Math.round(h.y+j.height/2)};f.style.left=h.x+"px";f.style.top=h.y+"px"}}}});var d=c.canvas.getSize(),e=Math.min;c.config.levelDistance=e(d.width,d.height)/2-a.offset-a.sliceOffset;this.sb=c;this.canvas=this.sb.canvas;
this.canvas.getCtx().globalCompositeOperation="lighter"},loadJSON:function(a){var b=i.time(),c=[],d=this.sb,e=i.splat(a.label),f=e.length,g=i.splat(a.color||this.colors),h=g.length,j=this.config,k=!!j.type.split(":")[1],l=j.animate;f=f==1;var m=0;a=a.values;for(var n=a.length;m<n;m++){var p=a[m],r=i.splat(p.values);c.push({id:b+p.label,name:p.label,data:{value:r,$valueArray:r,$colorArray:f?i.splat(g[m%h]):g,$stringArray:e,$gradient:k,$config:j,$angularWidth:i.reduce(r,function(A,u){return A+u})},
children:[]})}d.loadJSON({id:b+"$root",name:"",data:{$type:"none",$width:1,$height:1},children:c});this.normalizeDims();d.refresh();l&&d.fx.animate({modes:["node-property:dimArray"],duration:1500})},updateJSON:function(a,b){if(!this.busy){this.busy=true;var c=this.sb,d=c.graph,e=this.config.animate,f=this;i.each(a.values,function(g){var h=d.getByName(g.label);g=i.splat(g.values);if(h){h.setData("valueArray",g);h.setData("angularWidth",i.reduce(g,function(j,k){return j+k}));a.label&&h.setData("stringArray",
i.splat(a.label))}});this.normalizeDims();if(e){c.compute("end");c.fx.animate({modes:["node-property:dimArray:span","linear"],duration:1500,onComplete:function(){f.busy=false;b&&b.onComplete()}})}else c.refresh()}},select:function(a,b){if(this.config.hoveredColor){var c=this.selected;if(c.id!=a||c.name!=b){c.id=a;c.name=b;c.color=this.config.hoveredColor;this.sb.graph.eachNode(function(d){a==d.id?d.setData("border",c):d.setData("border",false)});this.sb.plot()}}},getLegend:function(){var a={},b;this.sb.graph.getNode(this.sb.root).eachAdjacency(function(e){b=
e.nodeTo});var c=b.getData("colorArray"),d=c.length;i.each(b.getData("stringArray"),function(e,f){a[e]=c[f%d]});return a},getMaxValue:function(){var a=0;this.sb.graph.eachNode(function(b){b=b.getData("valueArray");var c=0;i.each(b,function(d){c+=+d});a=a>c?a:c});return a},normalizeDims:function(){var a=0;this.sb.graph.getNode(this.sb.root).eachAdjacency(function(){a++});var b=this.getMaxValue()||1,c=this.config,d=c.animate,e=this.sb.config.levelDistance;this.sb.graph.eachNode(function(f){var g=0,
h=[];i.each(f.getData("valueArray"),function(k){g+=+k;h.push(1)});var j=h.length==1&&!c.updateHeights;if(d){f.setData("dimArray",i.map(f.getData("valueArray"),function(k){return j?e:k*e/b}),"end");f.getData("dimArray")||f.setData("dimArray",h)}else f.setData("dimArray",i.map(f.getData("valueArray"),function(k){return j?e:k*e/b}));f.setData("normalizedDim",g/b)})}});x.Tree={$extend:true,orientation:"left",subtreeOffset:8,siblingOffset:5,indent:10,multitree:false,align:"center"};q.Geom=new o({initialize:function(a){this.viz=
a;this.config=a.config;this.node=a.config.Node;this.edge=a.config.Edge},translate:function(a,b){b=i.splat(b);this.viz.graph.eachNode(function(c){i.each(b,function(d){c.getPos(d).$add(a)})})},setRightLevelToShow:function(a,b,c){var d=this.getRightLevelToShow(a,b),e=this.viz.labels,f=i.merge({execShow:true,execHide:true,onHide:i.empty,onShow:i.empty},c||{});a.eachLevel(0,this.config.levelsToShow,function(g){if(g._depth-a._depth>d){f.onHide(g);if(f.execHide){g.drawn=false;g.exist=false;e.hideLabel(g,
false)}}else{f.onShow(g);if(f.execShow)g.exist=true}});a.drawn=true},getRightLevelToShow:function(a,b){var c=this.config,d=c.levelsToShow;if(!c.constrained)return d;for(;!this.treeFitsInCanvas(a,b,d)&&d>1;)d--;return d}});v.TM={};v.TM.SliceAndDice=new o({compute:function(a){var b=this.graph.getNode(this.clickedNode&&this.clickedNode.id||this.root);this.controller.onBeforeCompute(b);var c=this.canvas.getSize(),d=this.config,e=c.width;c=c.height;this.graph.computeLevels(this.root,0,"ignore");b.getPos(a).setc(-e/
2,-c/2);b.setData("width",e,a);b.setData("height",c+d.titleHeight,a);this.computePositions(b,b,this.layout.orientation,a);this.controller.onAfterCompute(b)},computePositions:function(a,b,c,d){var e=0;a.eachSubnode(function(u){e+=u.getData("area",d)});var f=this.config,g=a.getData("width",d),h=a.getData("height",d)-f.titleHeight;a=a==b?1:b.getData("area",d)/e;var j,k,l,m,n;if(c=="h"){c="v";h=h;g=g*a;j="height";k="y";l="x";m=f.titleHeight;n=0}else{c="h";h=h*a;g=g;j="width";k="x";l="y";m=0;n=f.titleHeight}var p=
b.getPos(d);b.setData("width",g,d);b.setData("height",h,d);var r=0,A=this;b.eachSubnode(function(u){var z=u.getPos(d);z[k]=r+p[k]+m;z[l]=p[l]+n;A.computePositions(b,u,c,d);r+=u.getData(j,d)})}});v.TM.Area={compute:function(a){a=a||"current";var b=this.graph.getNode(this.clickedNode&&this.clickedNode.id||this.root);this.controller.onBeforeCompute(b);var c=this.config,d=this.canvas.getSize(),e=d.width;d=d.height;var f=c.offset,g=e-f;f=d-f;this.graph.computeLevels(this.root,0,"ignore");b.getPos(a).setc(-e/
2,-d/2);b.setData("width",e,a);b.setData("height",d,a);this.computePositions(b,{top:-d/2+c.titleHeight,left:-e/2,width:g,height:f-c.titleHeight},a);this.controller.onAfterCompute(b)},computeDim:function(a,b,c,d,e,f){if(a.length+b.length==1)this.layoutLast(a.length==1?a:b,c,d,f);else{if(a.length>=2&&b.length==0)b=[a.shift()];if(a.length==0)b.length>0&&this.layoutRow(b,c,d,f);else{var g=a[0];if(e(b,c)>=e([g].concat(b),c))this.computeDim(a.slice(1),b.concat([g]),c,d,e,f);else{b=this.layoutRow(b,c,d,
f);this.computeDim(a,[],b.dim,b,e,f)}}}},worstAspectRatio:function(a,b){if(!a||a.length==0)return Number.MAX_VALUE;for(var c=0,d=0,e=Number.MAX_VALUE,f=0,g=a.length;f<g;f++){var h=a[f]._area;c+=h;e=e<h?e:h;d=d>h?d:h}f=b*b;c=c*c;return Math.max(f*d/c,c/(f*e))},avgAspectRatio:function(a,b){if(!a||a.length==0)return Number.MAX_VALUE;for(var c=0,d=0,e=a.length;d<e;d++){var f=a[d]._area/b;c+=b>f?b/f:f/b}return c/e},layoutLast:function(a,b,c,d){a=a[0];a.getPos(d).setc(c.left,c.top);a.setData("width",c.width,
d);a.setData("height",c.height,d)}};v.TM.Squarified=new o({Implements:v.TM.Area,computePositions:function(a,b,c){var d=this.config;this.layout.orientation=b.width>=b.height?"h":"v";var e=a.getSubnodes([1,1],"ignore");if(e.length>0){this.processChildrenLayout(a,e,b,c);a=0;for(var f=e.length;a<f;a++){var g=e[a],h=d.offset;b=g.getData("height",c)-h-d.titleHeight;h=g.getData("width",c)-h;var j=g.getPos(c);b={width:h,height:b,top:j.y+d.titleHeight,left:j.x};this.computePositions(g,b,c)}}},processChildrenLayout:function(a,
b,c,d){a=c.width*c.height;var e,f=b.length,g=0,h=[];for(e=0;e<f;e++){h[e]=parseFloat(b[e].getData("area",d));g+=h[e]}for(e=0;e<f;e++)b[e]._area=a*h[e]/g;a=this.layout.horizontal()?c.height:c.width;b.sort(function(j,k){var l=k._area-j._area;return l?l:k.id==j.id?0:k.id<j.id?1:-1});e=[b[0]];this.squarify(b.slice(1),e,a,c,d)},squarify:function(a,b,c,d,e){this.computeDim(a,b,c,d,this.worstAspectRatio,e)},layoutRow:function(a,b,c,d){return this.layout.horizontal()?this.layoutV(a,b,c,d):this.layoutH(a,
b,c,d)},layoutV:function(a,b,c,d){var e=0;i.each(a,function(l){e+=l._area});b=e/b;for(var f=0,g=0,h=a.length;g<h;g++){var j=a[g]._area/b,k=a[g];k.getPos(d).setc(c.left,c.top+f);k.setData("width",b,d);k.setData("height",j,d);f+=j}a={height:c.height,width:c.width-b,top:c.top,left:c.left+b};a.dim=Math.min(a.width,a.height);a.dim!=a.height&&this.layout.change();return a},layoutH:function(a,b,c,d){var e=0;i.each(a,function(m){e+=m._area});for(var f=e/b,g=c.top,h=0,j=0,k=a.length;j<k;j++){var l=a[j];b=
l._area/f;l.getPos(d).setc(c.left+h,g);l.setData("width",b,d);l.setData("height",f,d);h+=b}a={height:c.height-f,width:c.width,top:c.top+f,left:c.left};a.dim=Math.min(a.width,a.height);a.dim!=a.width&&this.layout.change();return a}});v.TM.Strip=new o({Implements:v.TM.Area,computePositions:function(a,b,c){var d=a.getSubnodes([1,1],"ignore"),e=this.config;if(d.length>0){this.processChildrenLayout(a,d,b,c);a=0;for(var f=d.length;a<f;a++){var g=d[a],h=e.offset;b=g.getData("height",c)-h-e.titleHeight;h=
g.getData("width",c)-h;var j=g.getPos(c);b={width:h,height:b,top:j.y+e.titleHeight,left:j.x};this.computePositions(g,b,c)}}},processChildrenLayout:function(a,b,c,d){a=c.width*c.height;var e,f=b.length,g=0,h=[];for(e=0;e<f;e++){h[e]=+b[e].getData("area",d);g+=h[e]}for(e=0;e<f;e++)b[e]._area=a*h[e]/g;a=this.layout.horizontal()?c.width:c.height;e=[b[0]];this.stripify(b.slice(1),e,a,c,d)},stripify:function(a,b,c,d,e){this.computeDim(a,b,c,d,this.avgAspectRatio,e)},layoutRow:function(a,b,c,d){return this.layout.horizontal()?
this.layoutH(a,b,c,d):this.layoutV(a,b,c,d)},layoutV:function(a,b,c,d){var e=0;i.each(a,function(m){e+=m._area});for(var f=e/b,g=0,h=0,j=a.length;h<j;h++){var k=a[h],l=k._area/f;k.getPos(d).setc(c.left,c.top+(b-l-g));k.setData("width",f,d);k.setData("height",l,d);g+=l}return{height:c.height,width:c.width-f,top:c.top,left:c.left+f,dim:b}},layoutH:function(a,b,c,d){var e=0;i.each(a,function(n){e+=n._area});for(var f=e/b,g=c.height-f,h=0,j=0,k=a.length;j<k;j++){var l=a[j],m=l._area/f;l.getPos(d).setc(c.left+
h,c.top+g);l.setData("width",m,d);l.setData("height",f,d);h+=m}return{height:c.height-f,width:c.width,top:c.top,left:c.left,dim:b}}});$jit.TM={};var s=$jit.TM;$jit.TM.$extend=true;s.Base={layout:{orientation:"h",vertical:function(){return this.orientation=="v"},horizontal:function(){return this.orientation=="h"},change:function(){this.orientation=this.vertical()?"h":"v"}},initialize:function(a){this.controller=this.config=i.merge(x("Canvas","Node","Edge","Fx","Controller","Tips","NodeStyles","Events",
"Navigation","Label"),{orientation:"h",titleHeight:13,offset:2,levelsToShow:0,constrained:false,animate:false,Node:{type:"rectangle",overridable:true,width:3,height:3,color:"#444"},Label:{textAlign:"center",textBaseline:"top"},Edge:{type:"none"},duration:700,fps:45},a);this.layout.orientation=this.config.orientation;a=this.config;if(a.useCanvas){this.canvas=a.useCanvas;this.config.labelContainer=this.canvas.id+"-label"}else{if(a.background)a.background=i.merge({type:"Circles"},a.background);this.canvas=
new F(this,a);this.config.labelContainer=(typeof a.injectInto=="string"?a.injectInto:a.injectInto.id)+"-label"}this.graphOptions={complex:true,Node:{selected:false,exist:true,drawn:true}};this.graph=new q(this.graphOptions,this.config.Node,this.config.Edge);this.labels=new s.Label[a.Label.type](this);this.fx=new s.Plot(this);this.op=new s.Op(this);this.group=new s.Group(this);this.geom=new s.Geom(this);this.clickedNode=null;this.busy=false;this.initializeExtras()},refresh:function(){if(!this.busy){this.busy=
true;var a=this;if(this.config.animate){this.compute("end");this.config.levelsToShow>0&&this.geom.setRightLevelToShow(this.graph.getNode(this.clickedNode&&this.clickedNode.id||this.root));this.fx.animate(i.merge(this.config,{modes:["linear","node-property:width:height"],onComplete:function(){a.busy=false}}))}else{if(this.config.Label.type!="Native"){a=this;this.graph.eachNode(function(b){a.labels.hideLabel(b,false)})}this.busy=false;this.compute();this.config.levelsToShow>0&&this.geom.setRightLevelToShow(this.graph.getNode(this.clickedNode&&
this.clickedNode.id||this.root));this.plot()}}},plot:function(){this.fx.plot()},leaf:function(a){return a.getSubnodes([1,1],"ignore").length==0},enter:function(a){if(!this.busy){this.busy=true;var b=this,c=this.config,d=this.graph,e=this.clickedNode,f={onComplete:function(){c.levelsToShow>0&&b.geom.setRightLevelToShow(a);if(c.levelsToShow>0||c.request)b.compute();if(c.animate){d.nodeList.setData("alpha",0,"end");a.eachSubgraph(function(g){g.setData("alpha",1,"end")},"ignore");b.fx.animate({duration:500,
modes:["node-property:alpha"],onComplete:function(){b.clickedNode=a;b.compute("end");b.clickedNode=e;b.fx.animate({modes:["linear","node-property:width:height"],duration:1E3,onComplete:function(){b.busy=false;b.clickedNode=a}})}})}else{b.busy=false;b.clickedNode=a;b.refresh()}}};c.request?this.requestNodes(a,f):f.onComplete()}},out:function(){if(!this.busy){this.busy=true;this.events.hoveredNode=false;var a=this,b=this.config,c=this.graph,d=c.getNode(this.clickedNode&&this.clickedNode.id||this.root).getParents()[0],
e=this.clickedNode;if(d){callback={onComplete:function(){a.clickedNode=d;if(b.request)a.requestNodes(d,{onComplete:function(){a.compute();a.plot();a.busy=false}});else{a.compute();a.plot();a.busy=false}}};b.levelsToShow>0&&this.geom.setRightLevelToShow(d);if(b.animate){this.clickedNode=d;this.compute("end");this.clickedNode=e;this.fx.animate({modes:["linear","node-property:width:height"],duration:1E3,onComplete:function(){a.clickedNode=d;c.eachNode(function(f){f.setDataset(["current","end"],{alpha:[0,
1]})},"ignore");e.eachSubgraph(function(f){f.setData("alpha",1)},"ignore");a.fx.animate({duration:500,modes:["node-property:alpha"],onComplete:function(){callback.onComplete()}})}})}else callback.onComplete()}else this.busy=false}},requestNodes:function(a,b){var c=i.merge(this.controller,b),d=this.config.levelsToShow;if(c.request){var e=[],f=a._depth;a.eachLevel(0,d,function(g){var h=d-(g._depth-f);if(g.drawn&&!g.anySubnode()&&h>0){e.push(g);g._level=h}});this.group.requestNodes(e,c)}else c.onComplete()}};
s.Op=new o({Implements:q.Op,initialize:function(a){this.viz=a}});s.Geom=new o({Implements:q.Geom,getRightLevelToShow:function(){return this.viz.config.levelsToShow},setRightLevelToShow:function(a){var b=this.getRightLevelToShow(),c=this.viz.labels;a.eachLevel(0,b+1,function(d){if(d._depth-a._depth>b){d.drawn=false;d.exist=false;d.ignore=true;c.hideLabel(d,false)}else{d.drawn=true;d.exist=true;delete d.ignore}});a.drawn=true;delete a.ignore}});s.Group=new o({initialize:function(a){this.viz=a;this.canvas=
a.canvas;this.config=a.config},requestNodes:function(a,b){var c=0,d=a.length,e=this.viz;d==0&&b.onComplete();for(var f=0;f<d;f++)b.request(a[f].id,a[f]._level,{onComplete:function(g,h){if(h&&h.children){h.id=g;e.op.sum(h,{type:"nothing"})}if(++c==d){e.graph.computeLevels(e.root,0);b.onComplete()}}})}});s.Plot=new o({Implements:q.Plot,initialize:function(a){this.viz=a;this.config=a.config;this.node=this.config.Node;this.edge=this.config.Edge;this.animation=new P;this.nodeTypes=new s.Plot.NodeTypes;
this.edgeTypes=new s.Plot.EdgeTypes;this.labels=a.labels},plot:function(a,b){var c=this.viz,d=c.graph;c.canvas.clear();this.plotTree(d.getNode(c.clickedNode&&c.clickedNode.id||c.root),i.merge(c.config,a||{},{withLabels:true,hideLabels:false,plotSubtree:function(e){return e.anySubnode("exist")}}),b)}});s.Label={};s.Label.Native=new o({Implements:q.Label.Native,initialize:function(a){this.config=a.config;this.leaf=a.leaf},renderLabel:function(a,b){if(this.leaf(b)||this.config.titleHeight){var c=b.pos.getc(true),
d=a.getCtx(),e=b.getData("width");b.getData("height");d.fillText(b.name,c.x+e/2,c.y,e)}}});s.Label.SVG=new o({Implements:q.Label.SVG,initialize:function(a){this.viz=a;this.leaf=a.leaf;this.config=a.config},placeLabel:function(a,b,c){var d=b.pos.getc(true),e=this.viz.canvas,f=e.translateOffsetX,g=e.translateOffsetY,h=e.scaleOffsetX,j=e.scaleOffsetY;e=e.getSize();d={x:Math.round(d.x*h+f+e.width/2),y:Math.round(d.y*j+g+e.height/2)};a.setAttribute("x",d.x);a.setAttribute("y",d.y);if(!this.leaf(b)&&!this.config.titleHeight)a.style.display=
"none";c.onPlaceLabel(a,b)}});s.Label.HTML=new o({Implements:q.Label.HTML,initialize:function(a){this.viz=a;this.leaf=a.leaf;this.config=a.config},placeLabel:function(a,b,c){var d=b.pos.getc(true),e=this.viz.canvas,f=e.translateOffsetX,g=e.translateOffsetY,h=e.scaleOffsetX,j=e.scaleOffsetY;e=e.getSize();d={x:Math.round(d.x*h+f+e.width/2),y:Math.round(d.y*j+g+e.height/2)};f=a.style;f.left=d.x+"px";f.top=d.y+"px";f.width=b.getData("width")*h+"px";f.height=b.getData("height")*j+"px";f.zIndex=b._depth*
100;f.display="";if(!this.leaf(b)&&!this.config.titleHeight)a.style.display="none";c.onPlaceLabel(a,b)}});s.Plot.NodeTypes=new o({none:{render:i.empty},rectangle:{render:function(a,b){var c=this.viz.leaf(a),d=this.config,e=d.offset,f=d.titleHeight,g=a.pos.getc(true),h=a.getData("width"),j=a.getData("height"),k=a.getData("border"),l=b.getCtx(),m=g.x+e/2,n=g.y+e/2;if(!(h<=e||j<=e))if(c){if(d.cushion){c=l.createRadialGradient(m+(h-e)/2,n+(j-e)/2,1,m+(h-e)/2,n+(j-e)/2,h<j?j:h);d=a.getData("color");f=
i.rgbToHex(i.map(i.hexToRgb(d),function(p){return p*0.2>>0}));c.addColorStop(0,d);c.addColorStop(1,f);l.fillStyle=c}l.fillRect(m,n,h-e,j-e);if(k){l.save();l.strokeStyle=k;l.strokeRect(m,n,h-e,j-e);l.restore()}}else if(f>0){l.fillRect(g.x+e/2,g.y+e/2,h-e,f-e);if(k){l.save();l.strokeStyle=k;l.strokeRect(g.x+e/2,g.y+e/2,h-e,j-e);l.restore()}}},contains:function(a,b){if(this.viz.clickedNode&&!a.isDescendantOf(this.viz.clickedNode.id)||a.ignore)return false;var c=a.pos.getc(true),d=a.getData("width"),
e=this.viz.leaf(a)?a.getData("height"):this.config.titleHeight;return this.nodeHelper.rectangle.contains({x:c.x+d/2,y:c.y+e/2},b,d,e)}}});s.Plot.EdgeTypes=new o({none:i.empty});s.SliceAndDice=new o({Implements:[E,B,s.Base,v.TM.SliceAndDice]});s.Squarified=new o({Implements:[E,B,s.Base,v.TM.Squarified]});s.Strip=new o({Implements:[E,B,s.Base,v.TM.Strip]})})();

